"""Idempotent post-pass for modal accessibility and recovered shot-detail trigger."""
from pathlib import Path
import re
ROOT=Path(__file__).resolve().parents[1]; p=ROOT/'index.html'; t=p.read_text(encoding='utf-8')
# Field Card: actual modal behavior (background inert) + focus trap/focus restore.
old_re=r"function initAccessibleFieldCard\(\)\{const m=document\.getElementById\('field-card-modal'\);if\(!m\)return;let last=null;window\.openFieldCard=function\(\)\{.*?\}\);\}"
new="""function initAccessibleFieldCard(){const m=document.getElementById('field-card-modal');if(!m)return;let last=null,inerted=[];window.openFieldCard=function(){last=document.activeElement;inerted=[...document.body.children].filter(el=>el!==m&&!el.inert&&!['SCRIPT','STYLE'].includes(el.tagName));inerted.forEach(el=>el.inert=true);m.classList.add('fc-modal-open');m.setAttribute('aria-hidden','false');document.body.classList.add('fc-modal-lock');const first=m.querySelector('button,[href],input,select,textarea,[tabindex]:not([tabindex=\"-1\"])');setTimeout(()=>first?.focus(),0)};window.closeFieldCard=function(){m.classList.remove('fc-modal-open');m.setAttribute('aria-hidden','true');document.body.classList.remove('fc-modal-lock');inerted.forEach(el=>el.inert=false);inerted=[];last?.focus?.()};m.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();closeFieldCard();return}if(e.key!=='Tab')return;const f=[...m.querySelectorAll('button,[href],input,select,textarea,[tabindex]:not([tabindex=\"-1\"])')].filter(x=>!x.disabled&&x.offsetParent!==null);if(!f.length)return;const first=f[0],lastEl=f[f.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();lastEl.focus()}else if(!e.shiftKey&&document.activeElement===lastEl){e.preventDefault();first.focus()}});}"""
# simpler exact replacement when the pre-final version is present
pre="""function initAccessibleFieldCard(){const m=document.getElementById('field-card-modal');if(!m)return;let last=null;window.openFieldCard=function(){last=document.activeElement;m.classList.add('fc-modal-open');m.setAttribute('aria-hidden','false');document.body.classList.add('fc-modal-lock');const first=m.querySelector('button,[href],input,select,textarea,[tabindex]:not([tabindex=\"-1\"])');setTimeout(()=>first?.focus(),0)};window.closeFieldCard=function(){m.classList.remove('fc-modal-open');m.setAttribute('aria-hidden','true');document.body.classList.remove('fc-modal-lock');last?.focus?.()};m.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();closeFieldCard();return}if(e.key!=='Tab')return;const f=[...m.querySelectorAll('button,[href],input,select,textarea,[tabindex]:not([tabindex=\"-1\"])')].filter(x=>!x.disabled&&x.offsetParent!==null);if(!f.length)return;const first=f[0],lastEl=f[f.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();lastEl.focus()}else if(!e.shiftKey&&document.activeElement===lastEl){e.preventDefault();first.focus()}});}"""
if pre in t:t=t.replace(pre,new,1)
# CSS additions once.
if '#shot-modal{width:min(900px' not in t:
    t=t.replace('/* SOTA_ENHANCEMENTS_END */','#shot-modal{width:min(900px,calc(100% - 18px));max-height:92dvh;border:0;border-radius:20px;padding:0;box-shadow:0 30px 90px rgba(2,6,23,.38)}#shot-modal::backdrop{background:rgba(2,6,23,.70);backdrop-filter:blur(6px)}#shot-modal .shot-modal-card{max-height:92dvh;overflow:auto;background:#fff}.shot-card{content-visibility:auto;contain-intrinsic-size:auto 900px}\n/* SOTA_ENHANCEMENTS_END */',1)
# Migrate old custom detail container to native dialog.
start=t.find('<div id="shot-modal"')
end=t.find('\n\n<nav class="mobile-bottom-nav',start) if start>=0 else -1
if start>=0 and end>start:
    dlg='''<dialog id="shot-modal" aria-labelledby="modal-title"><div class="shot-modal-card"><div class="flex items-center justify-between p-4 border-b border-slate-200 sticky top-0 bg-white z-10"><h3 id="modal-title" class="font-bold text-lg">Detalle de toma</h3><button type="button" onclick="document.getElementById('shot-modal').close()" class="sota-btn" aria-label="Cerrar detalle">✕</button></div><div id="modal-body" class="p-6"></div></div></dialog>'''
    t=t[:start]+dlg+t[end:]
# Add trigger to dynamic shot card if absent.
if 'Abrir detalle ampliado' not in t:
    anchor='''          ${subjectView.safety ? `<p class="text-[10px] text-red-700 font-bold mt-1">${subjectView.safety}</p>` : ''}\n        </div>'''
    if anchor in t:t=t.replace(anchor,anchor+'''\n        <button type="button" class="sota-btn w-full" onclick="openModal('${plan.id}','${shot.id}')">🔎 Abrir detalle ampliado</button>''',1)
# Migrate old open/close behavior if present.
t=t.replace("""  document.getElementById('shot-modal').classList.remove('hidden');\n  document.getElementById('shot-modal').classList.add('flex');\n}\n\nfunction closeModal(e) {\n  if (e.target.id === 'shot-modal') {\n    document.getElementById('shot-modal').classList.add('hidden');\n    document.getElementById('shot-modal').classList.remove('flex');\n  }\n}""","""  const dialog=document.getElementById('shot-modal'); if(!dialog.open) dialog.showModal();\n}\n\nfunction closeModal(e) { if (e.target.id === 'shot-modal') e.target.close(); }""",1)
t=t.replace('<img src="${assetUrl(diagramPath)}" class="w-full rounded-lg mb-4" alt="Diagrama ampliado" />','<img loading="eager" decoding="async" src="${assetUrl(diagramPath)}" class="w-full rounded-lg mb-4" alt="Diagrama ampliado" />',1)
t=t.replace('loading="lazy" decoding="async" src="${assetUrl(diagramPath)}" alt="Diagrama ${shot.id} ${currentVariant}" loading="lazy" decoding="async"','loading="lazy" decoding="async" src="${assetUrl(diagramPath)}" alt="Diagrama ${shot.id} ${currentVariant}"')
p.write_text(t,encoding='utf-8');print('final interaction pass complete')
