"""
plans_data.py — Canonical data for the Canon 6D San Isidro photo planner.

Single source of truth used by:
  - generate_diagrams.py (produces PNGs)
  - The HTML site (loads plans.json exported from this file)

All distances in meters. All angles in degrees. Settings as strings (camera display style).
"""

# ---------------------------------------------------------------------------
# GEAR (Canon 6D Mark I + lenses)
# ---------------------------------------------------------------------------
GEAR = {
    "camera": {
        "name": "Canon EOS 6D Mark I",
        "sensor": "Full-frame CMOS 35.8 × 23.9 mm",
        "mp": "20.2 MP",
        "iso": "100–25600 (exp 50–102400)",
        "max_shutter": "1/4000 s",
        "bulb": True,
        "af_points": 11,
        "vf_coverage": "97%",
        "fps": 4.5,
        "mount": "EF",
    },
    "lenses": [
        {"name": "Canon EF 35mm f/2 IS USM", "focal": 35, "max_ap": 2.0, "min_focus_m": 0.24, "filter_mm": 67, "type": "prime", "h_fov": 54.2, "v_fov": 37.7},
        {"name": "Canon EF 50mm f/1.8 STM", "focal": 50, "max_ap": 1.8, "min_focus_m": 0.35, "filter_mm": 49, "type": "prime", "h_fov": 39.4, "v_fov": 26.9},
        {"name": "Canon EF 85mm f/1.8 USM", "focal": 85, "max_ap": 1.8, "min_focus_m": 0.85, "filter_mm": 58, "type": "prime", "h_fov": 23.8, "v_fov": 16.0},
        {"name": "Canon EF 35–80mm f/4–5.6 III", "focal": "35-80", "max_ap": "4-5.6", "min_focus_m": 0.40, "filter_mm": 52, "type": "zoom", "h_fov_35": 54.2, "h_fov_80": 25.2},
    ],
}

# ---------------------------------------------------------------------------
# COMPOSITION RULES (quick reference for tooltips)
# ---------------------------------------------------------------------------
COMPOSITION_RULES = {
    "tercios":         {"es": "Regla de tercios",        "en": "Rule of thirds",        "tip": "Coloca elementos clave en los tercios o intersecciones. No abuses: simetría central a veces comunica más."},
    "perspectiva":     {"es": "Perspectiva",              "en": "Perspective",            "tip": "Líneas convergentes dan profundidad. La perspectiva cambia al MOVER la cámara; cambiar de focal desde el mismo punto sólo cambia el encuadre."},
    "simetria":        {"es": "Simetría",                 "en": "Symmetry",               "tip": "Reflejo exacto alrededor de un eje. Ideal en arquitectura; evita si la escena es caótica."},
    "enmarcado":       {"es": "Enmarcado",                "en": "Framing",                "tip": "Usa elementos del entorno (arcos, ramas) para enmarcar al sujeto. Cuidado con recortes raros."},
    "espacio_neg":     {"es": "Espacio negativo",         "en": "Negative space",         "tip": "Deja aire alrededor del sujeto para aislarlo y dar respiración. No dejes tanto que el sujeto se pierda."},
    "punto_interes":   {"es": "Punto de interés",         "en": "Point of interest",      "tip": "Un único foco visual claro. Si hay varios compitiendo, la imagen pierde fuerza."},
    "minimalismo":     {"es": "Minimalismo",              "en": "Minimalism",             "tip": "Resta elementos hasta lo esencial. Cuidado: minimalismo ≠ vacío sin intención."},
    "capas":           {"es": "Capas",                    "en": "Layers",                 "tip": "Foreground/midground/background para profundidad real, no solo por perspectiva."},
}

# ---------------------------------------------------------------------------
# CAMERA ANGLES (Spanish/English)
# ---------------------------------------------------------------------------
CAMERA_ANGLES = {
    "central":      {"es": "Central",      "en": "Eye-level",   "height_factor": 1.0,  "tilt": 0,   "effect": "Neutro, igualdad sujeto-espectador"},
    "picado":       {"es": "Picado",       "en": "High angle",  "height_factor": 1.5,  "tilt": -20, "effect": "Sujeto se ve menor, vulnerable"},
    "contrapicado": {"es": "Contrapicado", "en": "Low angle",   "height_factor": 0.4,  "tilt": 20,  "effect": "Sujeto agrandado, dominante, heroico"},
    "nadir":        {"es": "Nadir",        "en": "Nadir",       "height_factor": 0.15, "tilt": 90,  "effect": "Cámara debajo del sujeto, eje vertical hacia arriba; dramático y abstracto"},
    "cenital":      {"es": "Cenital",      "en": "Top-down",    "height_factor": 2.5,  "tilt": -90, "effect": "Cámara sobre el sujeto, eje vertical hacia abajo; orden y geometría"},
    "dutch":        {"es": "Plano holandés","en": "Dutch angle","height_factor": 1.0,  "tilt": 0,   "roll": 15, "effect": "Tensión, desequilibrio"},
}

# ---------------------------------------------------------------------------
# TECHNIQUES — definitions used across all plans
# ---------------------------------------------------------------------------
TECHNIQUES = {
    "mucha_pdc":      {"es": "Mucha Profundidad de Campo", "en": "Deep DoF",            "icon": "layer-group"},
    "poca_pdc":       {"es": "Poca Profundidad de Campo",  "en": "Shallow DoF",         "icon": "circle-dot"},
    "congelado":      {"es": "Efecto Congelado",           "en": "Frozen motion",       "icon": "snowflake"},
    "barrido":        {"es": "Efecto Barrido",             "en": "Panning",             "icon": "arrows-left-right"},
    "fantasma":       {"es": "Efecto Fantasma",            "en": "Ghost effect",        "icon": "ghost"},
    "lightpainting":  {"es": "Lightpainting",              "en": "Light painting",      "icon": "wand-magic-sparkles"},
    "larga_exp":      {"es": "Larga Exposición",           "en": "Long exposure",       "icon": "hourglass-half"},
    "zooming":        {"es": "Zooming",                    "en": "Zoom burst",          "icon": "magnifying-glass-arrow"},
}

# ---------------------------------------------------------------------------
# FIELD-CARD BASELINES — validated starting points, not rigid exposure laws
# ---------------------------------------------------------------------------
FIELD_BASELINES = {
    "mucha_pdc_1": {"lens": "35mm", "aperture": "f/11", "shutter": "1/125+", "iso": "100–400", "af": "One Shot · foco ≈4 m", "geometry": "FG ≥2 m · sujeto ≈4 m · fondo ≥10 m"},
    "mucha_pdc_2": {"lens": "35mm / zoom @35", "aperture": "f/8–11", "shutter": "1/125+", "iso": "100–400", "af": "One Shot · eje central", "geometry": "sujeto ≈5–6 m · cámara nivelada"},
    "poca_pdc_1": {"lens": "85mm", "aperture": "f/1.8", "shutter": "1/500+", "iso": "Auto", "af": "One Shot · ojo cercano", "geometry": "sujeto ≈3 m · fondo ≥8 m DETRÁS"},
    "poca_pdc_2": {"lens": "50mm", "aperture": "f/1.8", "shutter": "1/250+", "iso": "Auto", "af": "One Shot · ojo/detalle", "geometry": "sujeto ≈2–2.5 m · fondo ≥5 m detrás"},
    "congelado": {"lens": "85mm", "aperture": "f/2.8", "shutter": "1/2000", "iso": "Auto", "af": "AI Servo · centro · ráfaga", "geometry": "sujeto ≈6–8 m · pre-seguir"},
    "barrido": {"lens": "50mm", "aperture": "Tv / auto", "shutter": "1/40", "iso": "100", "af": "AI Servo · seguimiento", "geometry": "trayectoria lateral / casi paralela"},
    "fantasma": {"lens": "35mm", "aperture": "f/8", "shutter": "1 s", "iso": "100", "af": "pre-enfoca → MF · trípode", "geometry": "fondo fijo · persona cruza cuadro"},
    "lightpainting": {"lens": "35mm", "aperture": "f/8", "shutter": "10 s", "iso": "100", "af": "pre-enfoca → MF · trípode", "geometry": "oscuridad · sujeto/objeto quieto"},
    "larga_exp": {"lens": "35mm", "aperture": "f/11", "shutter": "5–15 s", "iso": "100", "af": "pre-enfoca → MF · trípode", "geometry": "blue hour/noche · posición protegida"},
    "zooming": {"lens": "35–80mm", "aperture": "f/8", "shutter": "2 s", "iso": "100", "af": "pre-enfoca → MF · trípode", "geometry": "centro fuerte · cámara fija · 35↔80"},
}

# ---------------------------------------------------------------------------
# Helper to build a SHOT
# ---------------------------------------------------------------------------
def shot(shot_id, tech, lens_focal, ap, ss, iso, distance, bg_distance,
         composition, angle, height_m, pose, scene_notes,
         reasoning, dos, donts, day, afternoon, night,
         dog_subject, human_subject):
    # Field-card safety/clarity rules apply to every plan and every renderer.
    # Ghost = controlled human mover against a fixed scene; the dog stays out.
    # Long exposure around streets/traffic = no dog subject; prioritize tripod safety.
    if tech == "fantasma":
        dog_subject = {
            "pose": "walking_candid",
            "action": "Perro fuera de esta toma; usa una persona como sujeto móvil controlado."
        }
    elif tech == "larga_exp":
        dog_subject = {
            "pose": "sit_stay",
            "action": "Perro fuera de esta toma; prioriza trazas/escena y una posición protegida."
        }
    return {
        "id": shot_id,
        "technique": tech,
        "technique_label": TECHNIQUES[tech]["es"],
        "lens_focal": lens_focal,
        "aperture": ap,
        "shutter": ss,
        "iso": iso,
        "subject_distance_m": distance,
        "background_distance_m": bg_distance,
        "composition": composition,
        "composition_label": COMPOSITION_RULES[composition]["es"],
        "angle": angle,
        "angle_label": CAMERA_ANGLES[angle]["es"],
        "camera_height_m": height_m,
        "pose": pose,
        "scene_notes": scene_notes,
        "reasoning": reasoning,
        "dos": dos,
        "donts": donts,
        "settings_by_time": {"day": day, "afternoon": afternoon, "night": night},
        "subjects": {"dog": dog_subject, "human": human_subject},
    }


# ---------------------------------------------------------------------------
# POSES (curated archetypes — inspired by PoseArt by Pillb + standard portrait poses)
# ---------------------------------------------------------------------------
POSES_HUMAN = {
    "s_curve_standing":  "De pie, peso en una pierna, cadera ladeada, mano en bolsillo (S-curve)",
    "walking_candid":    "Caminando hacia la cámara, paso natural, mirada al frente",
    "looking_back":      "De espaldas, gira torso y cabeza sobre el hombro",
    "thinking_seated":   "Sentado, codo en rodilla, mano en mentón",
    "candid_laugh":      "Riendo, cabeza ligeramente atrás, mano cerca de la boca",
    "arms_crossed":      "De pie, brazos cruzados, hombros abiertos, mirada directa",
    "leaning_wall":      "Recargado en muro, un pie apoyado, relajado",
    "running_dynamic":   "Corriendo, en aire, brazos en oposición",
    "jumping_joy":       "Salto vertical, brazos arriba, sonrisa amplia",
    "portrait_3_4":      "Retrato 3/4, cuerpo girado 45°, cabeza hacia la cámara",
}

POSES_DOG = {
    "sit_stay":          "Sentado, atendiendo al dueño, orejas atentas",
    "lying_down":        "Echado, cabeza apoyada en patas, mirada suave",
    "running_fetch":     "Corriendo a atrapar pelota, patas extendidas",
    "standing_alert":    "Parado, orejas adelante, mirada fija",
    "jumping_catch":     "Salto vertical atrapando snack, patas recogidas",
    "walking_candid":    "Caminando olfateando, postura natural",
    "head_tilt":         "Sentado, cabeza ladeada (curioso)",
    "play_bow":          "Postura de juego: patas delanteras estiradas, cadera arriba",
    "backlit_silhouette":"De perfil contra luz de fondo, contorno definido",
    "treat_focus":       "Atendiendo un snack en mano del fotógrafo, ojos fijos",
}


# ===========================================================================
# PLAN A — Parque El Olivar (San Isidro)
# ===========================================================================
PLAN_A = {
    "id": "plan_a",
    "name": "Parque El Olivar — Bosque Histórico",
    "location": "Parque El Olivar, San Isidro (Av. La Encalada / Calle La Colonia)",
    "distance_from_home": "Acceso local; verifica tu ruta antes de salir",
    "best_window": "Mañana 06:20–08:00 (luz dorada) · Tarde 17:00–18:30",
    "why": "Olivares centenarios, senderos rectos, capas naturales de follaje, faroles coloniales. Permite deep-DoF con capas, shallow-DoF con aislamiento, panning con perros/ciclistas, y long-exposure con faroles al anochecer.",
    "palette": ["#3b5d3b", "#6b8e4e", "#c4a35a", "#d9d4c5"],
    "shots": [
        shot("A01", "mucha_pdc", 35, "f/11", "1/250", 200, 4.0, 12.0,
             "capas", "central", 1.55,
             POSES_HUMAN["portrait_3_4"],
             "Sendero central de olivos, sujeto a 4 m, hileras de olivos que convergen al fondo. Sujeto en tercio izquierdo del encuadre.",
             "El 35mm en FF da un FoV horizontal de 54°, suficiente para incluir 2-3 hileras de olivos como capas. A f/11 y 4 m de distancia el hiperfocal cae a ~5.1 m, así que TODO desde ~2.5 m hasta infinito queda nítido — exactamente lo que necesita 'mucha PDC'. El fondo a 12 m queda enfocado, mostrando las capas de árboles.",
             ["Dispara en modo Av con f/11, enfoque al sujeto, deja que la cámara elija velocidad", "Usa un pie de foto para evitar trepidación si la velocidad baja de 1/100", "Equilibra el horizonte con la regla de tercios vertical"],
             ["No uses 35mm a f/2 — perderías las capas del fondo, clave de esta composición", "No coloques al sujeto pegado al fondo (necesitas separación para que las capas se distingan)"],
             {"lens": "35mm", "aperture": "f/11", "shutter": "1/250", "iso": 200, "notes": "Mañana: luz lateral cálida, olivos a contraluz suave. Equilibra exposiciones con -0.3 EV."},
             {"lens": "35mm", "aperture": "f/11", "shutter": "1/125", "iso": 400, "notes": "Tarde: sol bajo, sombras largas. Cuidado con sombras duras en el rostro."},
             {"lens": "35mm", "aperture": "f/8", "shutter": "1/30", "iso": 1600, "notes": "Noche: faroles del parque. Sube ISO, abre a f/8 para mantener algo de PDC. Usa columna de trípode improvisada (muro bajo)."},
             {"pose": "treat_focus", "action": "Perro sentado atendiendo un snack en tu mano, mirada fija hacia la cámara"},
             {"pose": "portrait_3_4", "action": "Modelo 3/4, cuerpo girado 45° hacia la luz, manos relajadas"}),
        shot("A02", "mucha_pdc", "35-80@35", "f/8", "1/200", 200, 6.0, 20.0,
             "simetria", "central", 1.65,
             POSES_HUMAN["arms_crossed"],
             "Paseo peatonal entre dos hileras de palmeras/olivos. Sujeto en el centro exacto, ejes bilaterales a izquierda y derecha.",
             "La simetría exige que el sujeto esté en el centro óptico y la cámara perfectamente nivelada (usa el nivel del 6D). El zoom a 35mm f/8 da menor nitidez que el prime pero suficiente para Web/print mediano. Distancia 6 m para que el sujeto llene 1/3 del alto del encuadre.",
             ["Verifica simetría con la rejilla de pantalla del 6D", "Usa nivel electrónico o de zapata", "Equilibra luz izquierda/derecha (si hay sol lateral, busca sombra pareja)"],
             ["No rompas la simetría con elementos laterales asimétricos (basura, personas)", "No dispares descentrado — 5 cm arruinan el efecto"],
             {"lens": "35-80mm @35", "aperture": "f/8", "shutter": "1/200", "iso": 200, "notes": "Mañana: buena luz, busca alineación solar perfecta para sombras simétricas."},
             {"lens": "35-80mm @35", "aperture": "f/8", "shutter": "1/100", "iso": 400, "notes": "Tarde: sombras largas pueden romper la simetría; dispara cuando el sol está alto."},
             {"lens": "35-80mm @35", "aperture": "f/5.6", "shutter": "1/15", "iso": 1600, "notes": "Noche: con faroles simétricos, sube ISO a 3200 si es necesario."},
             {"pose": "sit_stay", "action": "Perro sentado perfectamente centrado, atendiendo"},
             {"pose": "arms_crossed", "action": "Modelo de pie, brazos cruzados, simetría frontal"}),
        shot("A03", "poca_pdc", 85, "f/1.8", "1/500", 200, 3.0, 8.0,
             "punto_interes", "central", 1.55,
             POSES_HUMAN["portrait_3_4"],
             "Retrato de cabeza y hombros. Sujeto contra un seto verde a 8 m. Fondo desenfocado en verde suave.",
             "El 85mm f/1.8 es EL retrato clásico: a 3 m da una distancia de enfoque de ~14 cm, así que ojos nítidos, orejas y pelo ya borrosos. Fondo a 8 m se convierte en mancha verde uniforme. El punto de interés único es el ojo más cercano.",
             ["Enfoca EXACTAMENTE en el ojo más cercano (usa AF punto central + recomposición)", "Dispara a f/1.8 o f/2 — no tengo miedo a abrir de más", "Si hay viento, dispara en ráfaga para capturar el instante de quietud del pelo"],
             ["No uses 85mm a f/8 — mata la razón de ser del lente", "No dispares demasiado lejos: a 6 m el 85mm da poca PDC y el sujeto queda chico en el encuadre"],
             {"lens": "85mm", "aperture": "f/2", "shutter": "1/1000", "iso": 200, "notes": "Mañana: sol suave lateral, fondo verde se satura con contraluz."},
             {"lens": "85mm", "aperture": "f/1.8", "shutter": "1/500", "iso": 200, "notes": "Tarde: hora dorada — el fondo verde brilla, sujeto con luz cálida."},
             {"lens": "85mm", "aperture": "f/1.8", "shutter": "1/60", "iso": 3200, "notes": "Noche: retrato con farol — cuidado con WB, prueba 3200K."},
             {"pose": "head_tilt", "action": "Perro con cabeza ladeada, ojos fijos en cámara"},
             {"pose": "portrait_3_4", "action": "Modelo girada 45°, mirada directa a cámara"}),
        shot("A04", "poca_pdc", 50, "f/1.8", "1/250", 200, 2.5, 5.0,
             "espacio_neg", "central", 1.40,
             POSES_HUMAN["looking_back"],
             "Sujeto de espaldas girándose sobre el hombro. Mucho espacio vacío a la derecha (dirección de la mirada). Fondo: olivo solitario desenfocado.",
             "El 50mm a f/1.8 y 2.5 m da ~25 cm de PDC — perfecto para medio cuerpo. El espacio negativo (3/4 del encuadre a la derecha) dirige la mirada del espectador hacia donde mira el sujeto. Fondo a 5 m con 50mm f/1.8 = mancha abstracta.",
             ["Coloca al sujeto en el tercio IZQUIERDO, mirando hacia el espacio vacío", "Espera un gesto natural del girarse (no pose rígida)", "Equilibra la exposición con -0.3 EV para preservar luces del cielo"],
             ["No llenes el espacio negativo con elementos extra (vaciado intencional)", "No dispares de frente — pierde el punto de 'sobre el hombro'"],
             {"lens": "50mm", "aperture": "f/2.2", "shutter": "1/500", "iso": 200, "notes": "Mañana: luz trasera, pelo brilla (rim light)."},
             {"lens": "50mm", "aperture": "f/1.8", "shutter": "1/250", "iso": 200, "notes": "Tarde dorada:WB cálido 5500K, contraste suave."},
             {"lens": "50mm", "aperture": "f/1.8", "shutter": "1/60", "iso": 3200, "notes": "Noche: usa un farol como contraluz detrás del sujeto."},
             {"pose": "backlit_silhouette", "action": "Perro de perfil contra luz trasera, contorno del pelo brilla"},
             {"pose": "looking_back", "action": "Modela girándose sobre el hombro, mirada a cámara"}),
        shot("A05", "congelado", 85, "f/2.8", "1/2000", 400, 6.0, 15.0,
             "minimalismo", "contrapicado", 0.60,
             POSES_HUMAN["jumping_joy"],
             "Sujeto saltando contra cielo despejado. Cámara baja (0.6 m) mirando hacia arriba, solo cielo como fondo.",
             "1/2000s congela el salto perfectamente. 85mm a 6 m da encuadre de medio cuerpo en el aire. Contrapicado agranda al sujeto y aísla contra el cielo (minimalismo por eliminación de fondo). f/2.8 mantiene algo de margen de enfoque en movimiento.",
             ["Usa AF AI Servo + selección de punto + burst de 4.5 fps", "Cuenta regresiva 3-2-1 con el sujeto para sincronizar el salto", "Dispara en JPG+RAW por si el AF falla en algunas tomas"],
             ["No dispares a 1/500 — el salto saldrá borroso", "No uses f/1.8 — el margen de PDC es tan fino que fallarás el enfoque"],
             {"lens": "85mm", "aperture": "f/4", "shutter": "1/4000", "iso": 200, "notes": "Mañana: cielo azul, sombras duras — usa reflector o flash de relleno."},
             {"lens": "85mm", "aperture": "f/2.8", "shutter": "1/2000", "iso": 400, "notes": "Tarde dorada: cielo con color, salto contraluz."},
             {"lens": "85mm", "aperture": "f/2.8", "shutter": "1/1000", "iso": 6400, "notes": "Noche: difícil, requiere flash; mejor posponer a día."},
             {"pose": "jumping_catch", "action": "Perro saltando a atrapar snack/frisbee, patas recogidas"},
             {"pose": "jumping_joy", "action": "Modelo saltando vertical, brazos arriba, sonrisa"}),
        shot("A06", "barrido", 50, "f/11", "1/30", 100, 6.0, 25.0,
             "tercios", "central", 1.0,
             POSES_HUMAN["running_dynamic"],
             "Sujeto corriendo / perro corriendo de izquierda a derecha. Cámara sigue el movimiento en arco. Fondo: árboles del parque a 25 m (serán streaks horizontales).",
             "1/30s con seguimiento horizontal: sujeto nítido, fondo en streaks. El 50mm a 6 m encuadra medio cuerpo en movimiento. Coloca al sujeto en el tercio derecho para que el movimiento 'entre' al encuadre. f/11 da algo de margen si falla el seguimiento.",
             ["Gira el torso siguiendo al sujeto antes, durante y DESPUÉS del disparo (no pares al clic)", "Usa AF AI Servo con punto central + burst", "Practica el movimiento en seco 3-4 veces antes"],
             ["No dispares estático — el barrido requiere movimiento de cámara", "No uses 1/250 — congela todo, pierde el efecto", "No dispares a f/1.8 — fallarás el enfoque en movimiento"],
             {"lens": "50mm", "aperture": "f/11", "shutter": "1/30", "iso": 100, "notes": "Mañana: luz fuerte permite 1/30 a ISO 100."},
             {"lens": "50mm", "aperture": "f/8", "shutter": "1/30", "iso": 200, "notes": "Tarde: luz más suave, mantén 1/30."},
             {"lens": "50mm", "aperture": "f/4", "shutter": "1/30", "iso": 1600, "notes": "Noche: con faroles, sube ISO; el barrido funciona con cualquier luz."},
             {"pose": "running_fetch", "action": "Perro corriendo horizontal a buscar pelota"},
             {"pose": "running_dynamic", "action": "Modelo corriendo, brazos en oposición"}),
        shot("A07", "fantasma", 35, "f/11", "2\"", 100, 5.0, 15.0,
             "enmarcado", "picado", 1.80,
             POSES_HUMAN["candid_laugh"],
             "Sujeto semi-quieto en arco de olivos (enmarcado natural). 2s de exposición: partes quietas (troncos, pies) nítidas, partes en movimiento (cabeza riendo, manos) ghost.",
             "2s a f/11 ISO 100 con luz ambiente del parque. El sujeto debe permanecer ~80% quieto — solo mover cabeza/manos. El arco de olivos enmarca y estabiliza visualmente. Picado ligero da superioridad al espectador y muestra el suelo con hojas.",
             ["Usa trípode IMPRESCINDIBLE o superficie estable", "Pide al sujeto: 'quédate quieto, mueve solo la cabeza al reír'", "Toma 3-4 versiones — el fantasma es aleatorio"],
             ["No dispares sin trípode — el fondo también saldrá movido", "No expongas más de 4s — el fantasma se desvanece demasiado"],
             {"lens": "35mm", "aperture": "f/16", "shutter": "2", "iso": 100, "notes": "Mañana: difícil — luz fuerte. Usa filtro ND si tienes."},
             {"lens": "35mm", "aperture": "f/16", "shutter": "2", "iso": 100, "notes": "Tarde: luz baja, ideal para 2s sin ND."},
             {"lens": "35mm", "aperture": "f/8", "shutter": "2", "iso": 400, "notes": "Noche: con faroles, 2s a f/8 ISO 400 es perfecto."},
             {"pose": "play_bow", "action": "Perro en postura de juego, cola moviéndose (cola será ghost, cuerpo quieto)"},
             {"pose": "candid_laugh", "action": "Modela riendo, cabeza atrás, manos cerca de la boca"}),
        shot("A08", "lightpainting", 35, "f/8", "Bulb 20\"", 100, 4.0, 10.0,
             "punto_interes", "central", 1.40,
             POSES_HUMAN["arms_crossed"],
             "Sujeto quieto a 4 m. Asistente traza con linterna a su alrededor (círculos, espirales, contorno). Oscuridad total salvo la linterna.",
             "Bulb 20s a f/8 ISO 100. La linterna debe moverse continuamente; cada punto de luz pinta en el sensor. El sujeto debe permanecer MUY quieto para no salir como ghost. f/8 da nitidez suficiente sin que el lightpainting se vea borroso.",
             ["Usa trípode + disparador remoto o 2s retardados", "El sujeto lleva ropa oscura para que la luz destaque", "La linterna: LED pequeño,_color blanco cálido o RGB"],
             ["No muevas la cámara — cualquier movimiento arruina el trazo", "No dejes la linterna apuntando al lente — crearás flare", "No uses ISO alto — se quemará la imagen"],
             {"lens": "35mm", "aperture": "f/16", "shutter": "Bulb 30", "iso": 100, "notes": "Mañana: imposible sin ND extremo. Mejor de noche."},
             {"lens": "35mm", "aperture": "f/16", "shutter": "Bulb 25", "iso": 100, "notes": "Tarde: solo en zona muy sombreada o túnel."},
             {"lens": "35mm", "aperture": "f/8", "shutter": "Bulb 20", "iso": 100, "notes": "Noche: ideal, oscuridad total del parque a las 19:30."},
             {"pose": "sit_stay", "action": "Perro sentado MUY quieto, dueño traza luz a su alrededor"},
             {"pose": "arms_crossed", "action": "Modela con brazos cruzados, asistente traza luz"}),
        shot("A09", "larga_exp", "35-80@50", "f/11", "15\"", 100, 20.0, 100.0,
             "espacio_neg", "central", 1.65,
             POSES_HUMAN["walking_candid"],
             "Cámara en trípode apuntando al cielo con copas de olivos. Sujeto camina lentamente por sendero lejano. 15s: el caminante se desvanece en ghost, las ramas quedan nítidas, las nubes en streaks.",
             "15s a f/11 ISO 100 con ND opcional. La larga exposición capta: nubes en movimiento (streaks), peatones como ghosts, ramas estáticas. Distancia 20 m para que el sujeto sea pequeño (punto de interés mínimo, mucho espacio negativo).",
             ["Trípode + disparador remoto IMPRESCINDIBLES", "Si hay mucho sol: ND8 o ND10", "Encuadra con cabeza fría antes de disparar — luego no puedes recomponer"],
             ["No toques la cámara durante la exposición", "No dispares con viento fuerte — las ramas también saldrán blur"],
             {"lens": "35-80mm @50", "aperture": "f/16", "shutter": "15", "iso": 100, "notes": "Mañana: ND10 obligatorio, algo de viento ayuda."},
             {"lens": "35-80mm @50", "aperture": "f/16", "shutter": "15", "iso": 100, "notes": "Tarde: ND8 suficiente, hora dorada añade color."},
             {"lens": "35-80mm @50", "aperture": "f/11", "shutter": "20", "iso": 200, "notes": "Noche: sin ND, faroles como estrellas de 6 puntas a f/11."},
             {"pose": "walking_candid", "action": "Perro caminando olfateando — será ghost suave"},
             {"pose": "walking_candid", "action": "Modela caminando lentamente — será ghost"}),
        shot("A10", "zooming", "35-80", "f/11", "2\"", 100, 8.0, 30.0,
             "perspectiva", "central", 1.55,
             POSES_HUMAN["portrait_3_4"],
             "Sujeto a 8 m en sendero. Durante los 2s de exposición gira el anillo del zoom de 35 a 80mm (o viceversa). El sujeto queda como punto fijo + estallido radial.",
             "2s a f/11 ISO 100. Gira el zoom uniformemente durante toda la exposición. El sujeto debe estar PERFECTAMENTE centrado — el zoom crea un efecto radial desde el centro óptico. Perspectiva forzada por las líneas de fuga del efecto zoom.",
             ["Practica el giro del zoom en seco: debe ser uniforme, ni rápido al inicio ni al final", "Sujeto al centro EXACTO del encuadre", "Trípode obligatorio"],
             ["No muevas la cámara mientras haces zoom — arruinarás el centro fijo", "No uses 1s — no da tiempo al giro completo"],
             {"lens": "35-80mm", "aperture": "f/16", "shutter": "2", "iso": 100, "notes": "Mañana: ND8 necesario para 2s."},
             {"lens": "35-80mm", "aperture": "f/16", "shutter": "2", "iso": 100, "notes": "Tarde: hora dorada + zoom burst = dramático."},
             {"lens": "35-80mm", "aperture": "f/8", "shutter": "2", "iso": 800, "notes": "Noche: con faroles, 2s a f/8 ISO 800 funciona."},
             {"pose": "sit_stay", "action": "Perro sentado al centro, quieto absoluto"},
             {"pose": "portrait_3_4", "action": "Modela 3/4 al centro, muy quieta"}),
    ],
}


# ===========================================================================
# PLAN B — Malecón de Miraflores / Costa Verde
# ===========================================================================
PLAN_B = {
    "id": "plan_b",
    "name": "Malecón de Miraflores — Costa Verde",
    "location": "Malecón Cisneros / Parque del Amor, Miraflores",
    "distance_from_home": "Acceso urbano; verifica tráfico y transporte",
    "best_window": "Tarde 16:30–18:30 (hora dorada + atardecer sobre el Pacífico) · Noche 19:00–21:00",
    "why": "Horizonte abierto del Pacífico, sol ocultándose en el mar (azimut 278°–288°), faroles del malecón, parapentes en movimiento. Ideal para larga exposición del mar, panning de parapentes, contrapicados contra el cielo, minimalismo con horizonte.",
    "palette": ["#0e4f6b", "#3b8dbd", "#f4a261", "#e76f51"],
    "shots": [
        shot("B01", "mucha_pdc", 35, "f/11", "1/500", 200, 5.0, 50.0,
             "capas", "central", 1.65,
             POSES_HUMAN["leaning_wall"],
             "Sujeto recargado en baranda del malecón. Capas: 1) baranda (FG), 2) sujeto (midground), 3) paseantes/parapentes (mid-far), 4) mar y horizonte (background), 5) cielo.",
             "El 35mm a 5 m cubre todos los planos. f/11 con hiperfocal ~5m da nitidez desde 2.5 m a infinito. Las capas se construyen con profundidad real: la baranda ocupa 1/6 inferior, el sujeto 1/3, el horizonte en el tercio superior.",
             ["Encuadra la baranda como línea diagonal FG", "Pon el horizonte en el tercio superior (no al centro)", "Verifica que el sujeto no se solape con elementos lejanos"],
             ["No dispares con marea subiendo si te paras muy cerca del borde (spray salino)", "No rompas las capas con un fondo caótico"],
             {"lens": "35mm", "aperture": "f/11", "shutter": "1/500", "iso": 200, "notes": "Mañana: cielo despejado, mar azul."},
             {"lens": "35mm", "aperture": "f/11", "shutter": "1/250", "iso": 200, "notes": "Tarde: hora dorada, todo brilla."},
             {"lens": "35mm", "aperture": "f/8", "shutter": "1/15", "iso": 1600, "notes": "Noche: faroles del malecón + largos tiempos."},
             {"pose": "standing_alert", "action": "Perro de pie junto a baranda, atendiendo al horizonte"},
             {"pose": "leaning_wall", "action": "Modela recargada en baranda, mirando al mar"}),
        shot("B02", "mucha_pdc", "35-80@35", "f/8", "1/250", 200, 8.0, 100.0,
             "espacio_neg", "central", 1.70,
             POSES_HUMAN["walking_candid"],
             "Sujeto caminando por la ciclovía del malecón. Mucho espacio a la izquierda (mar y cielo). Sujeto pequeño, horizonte en tercio inferior.",
             "El zoom a 35mm (no es tan nítido como el prime) a f/8 da suficiente PDC. 8 m de distancia para que el sujeto ocupe 1/4 del encuadre. Espacio negativo: 60% cielo+mar a la izquierda, sujeto como punto focal mínimo.",
             ["Espera un momento sin peatones cruzando", "Mantén el horizonte perfectamente horizontal", "Subexponer -0.7 EV para preservar detalle del cielo"],
             ["No incrustes al sujeto contra el horizonte (se pierde la cabeza)", "No uses f/5.6 — la PDC no será suficiente para mantener nítido el horizonte"],
             {"lens": "35-80mm @35", "aperture": "f/8", "shutter": "1/250", "iso": 200, "notes": "Mañana: brisa marina refresca, cielo azul profundo."},
             {"lens": "35-80mm @35", "aperture": "f/8", "shutter": "1/125", "iso": 400, "notes": "Tarde: hora dorada, contraste suave."},
             {"lens": "35-80mm @35", "aperture": "f/5.6", "shutter": "1/8", "iso": 3200, "notes": "Noche: necesitas trípode para 1/8; mejor posponer a día."},
             {"pose": "walking_candid", "action": "Perro caminando olfateando por la ciclovía"},
             {"pose": "walking_candid", "action": "Modela caminando lentamente, mirada al frente"}),
        shot("B03", "poca_pdc", 85, "f/1.8", "1/1000", 200, 2.5, 15.0,
             "punto_interes", "central", 1.55,
             POSES_HUMAN["candid_laugh"],
             "Retrato de medio cuerpo contra el horizonte del mar. Fondo desenfocado: mar como mancha azul/verde, sin horizonte definido.",
             "85mm a 2.5 m y f/1.8: PDC ≈ 8 cm. Ojos nítidos, resto del rostro ya blando. El mar a 15 m se convierte en textura abstracta. El punto de interés es el ojo más cercano, reforzado por la sonrisa natural.",
             ["Enfoca con punto central + recomposición suave (sin mover la distancia)", "Dispara en ráfaga para capturar el pico de la sonrisa", "Si hay sol directo: usa un reflector o sombra natural"],
             ["No uses 85mm a f/8 — matas el bokeh del mar", "No dispares contraluz sin reflector o flash de relleno"],
             {"lens": "85mm", "aperture": "f/2", "shutter": "1/2000", "iso": 200, "notes": "Mañana: sol fuerte, usa sombra natural."},
             {"lens": "85mm", "aperture": "f/1.8", "shutter": "1/1000", "iso": 200, "notes": "Tarde dorada: luz cálida, ideal."},
             {"lens": "85mm", "aperture": "f/1.8", "shutter": "1/60", "iso": 6400, "notes": "Noche: retrato con farol, problema de WB."},
             {"pose": "head_tilt", "action": "Perro con cabeza ladeada, ojos fijos"},
             {"pose": "candid_laugh", "action": "Modela riendo, gesto natural"}),
        shot("B04", "poca_pdc", 50, "f/1.8", "1/500", 200, 3.0, 8.0,
             "enmarcado", "central", 1.40,
             POSES_HUMAN["s_curve_standing"],
             "Sujeto enmarcado por la curva de una palmera o murete del malecón. El 'marco' natural cerca de la cámara desenfocado crea profundidad.",
             "50mm a 3 m y f/1.8: el marco cercano (palmera a 1 m) sale muy desenfocado, el sujeto a 3 m nítido en su plano, el fondo a 8 m suavemente borroso. Tres planos definidos por la PDC.",
             ["Encuentra un marco asimétrico (palmera a izquierda, no centrada)", "El marco debe ocupar 1/5 del encuadre, no más", "Equilibra la luz: si el marco está oscuro y el sujeto iluminado, perfecto"],
             ["No uses un marco que tape al sujeto (la palmera debe enmarcar, no ocultar)", "No dispares a f/4 — el marco saldrá demasiado nítido y competirá"],
             {"lens": "50mm", "aperture": "f/2", "shutter": "1/1000", "iso": 200, "notes": "Mañana: sol lateral ilumina el marco y el sujeto por igual."},
             {"lens": "50mm", "aperture": "f/1.8", "shutter": "1/500", "iso": 200, "notes": "Tarde: luz dorada, el marco se ve más cálido."},
             {"lens": "50mm", "aperture": "f/1.8", "shutter": "1/30", "iso": 3200, "notes": "Noche: con farol detrás del marco, efecto contraluz."},
             {"pose": "lying_down", "action": "Perro echado, murete del malecón lo enmarca"},
             {"pose": "s_curve_standing", "action": "Modela con pose S-curve, palmera enmarca"}),
        shot("B05", "congelado", 85, "f/2.8", "1/2500", 400, 15.0, 200.0,
             "tercios", "central", 1.65,
             POSES_HUMAN["running_dynamic"],
             "Parapente en vuelo bajo sobre el malecón. Cámara sigue al parapente. 1/2500s congela la vela y al piloto.",
             "El 85mm a 15 m encuadra un parapente medio. 1/2500s congela TODO incluyendo el viento en la vela. El parapente en el tercio superior derecho del encuadre (regla de tercios) deja espacio inferior para el mar/parque.",
             ["AF AI Servo + punto central + burst", "Pre-enfoca en la zona por donde pasan los parapentes", "Dispara en JPG+RAW, descarta los no nítidos"],
             ["No uses 1/500 — el parapente saldrá blando", "No abras a f/1.8 — el margen de PDC es mínimo a 15 m"],
             {"lens": "85mm", "aperture": "f/4", "shutter": "1/4000", "iso": 200, "notes": "Mañana: sol fuerte, parapentes tempranos."},
             {"lens": "85mm", "aperture": "f/2.8", "shutter": "1/2500", "iso": 400, "notes": "Tarde: luz dorada sobre las velas."},
             {"lens": "85mm", "aperture": "f/2.8", "shutter": "1/1250", "iso": 6400, "notes": "Noche: raro que haya parapentes nocturnos."},
             {"pose": "jumping_catch", "action": "Perro saltando a atrapar frisbee (si no hay parapente) — equivalente en concepto"},
             {"pose": "running_dynamic", "action": "Atleta/corredor en movimiento, mismo principio"}),
        shot("B06", "barrido", 50, "f/11", "1/30", 100, 8.0, 50.0,
             "tercios", "central", 1.10,
             POSES_HUMAN["running_dynamic"],
             "Ciclista o corredor del malecón. Cámara sigue el movimiento horizontal. Fondo: mar y malecón en streaks horizontales.",
             "1/30s con seguimiento lateral. 50mm a 8 m encuadra medio cuerpo en movimiento. El sujeto en el tercio derecho entrante, mirando hacia el espacio libre. f/11 da margen para fallos de seguimiento.",
             ["Posiciónate donde los ciclistas pasan predeciblemente", "Gira el torso: prep → dispara → continúa el giro 1s más", "Punto central AF + AI Servo + burst"],
             ["No pares el giro al disparar", "No uses 1/250 — congela todo"],
             {"lens": "50mm", "aperture": "f/11", "shutter": "1/30", "iso": 100, "notes": "Mañana: luz fuerte, ideal."},
             {"lens": "50mm", "aperture": "f/8", "shutter": "1/30", "iso": 200, "notes": "Tarde dorada: streaks más cálidos."},
             {"lens": "50mm", "aperture": "f/4", "shutter": "1/30", "iso": 1600, "notes": "Noche: faroles crean streaks luminosos."},
             {"pose": "running_fetch", "action": "Perro corriendo horizontal por la ciclovía"},
             {"pose": "running_dynamic", "action": "Ciclista o corredor pasando"}),
        shot("B07", "fantasma", 35, "f/11", "3\"", 100, 4.0, 20.0,
             "enmarcado", "picado", 1.80,
             POSES_HUMAN["thinking_seated"],
             "Sujeto sentado en un banco del malecón, mirando al mar. 3s: el sujeto quieto es nítido, los paseantes detrás son ghosts.",
             "3s a f/11 ISO 100. Sujeto quieto en banco (enmarcado por baranda), paseantes detrás se mueven y salen como ghosts. Picado ligero muestra el suelo del malecón y aísla al sujeto.",
             ["Trípode obligatorio", "Pide al sujeto: respira suave, no te muevas", "Toma 5-6 versiones para elegir el mejor ghost"],
             ["No muevas la cámara", "No dispares con viento fuerte — el pelo sale blur"],
             {"lens": "35mm", "aperture": "f/16", "shutter": "3", "iso": 100, "notes": "Mañana: ND10 obligatorio, difícil."},
             {"lens": "35mm", "aperture": "f/16", "shutter": "3", "iso": 100, "notes": "Tarde: hora dorada, ideal."},
             {"lens": "35mm", "aperture": "f/8", "shutter": "3", "iso": 400, "notes": "Noche: con faroles, perfecto."},
             {"pose": "sit_stay", "action": "Perro sentado quieto en banco, peatones pasan detrás"},
             {"pose": "thinking_seated", "action": "Modela sentada pensando, peatones ghosts detrás"}),
        shot("B08", "lightpainting", 35, "f/8", "Bulb 25\"", 100, 5.0, 30.0,
             "minimalismo", "central", 1.0,
             POSES_HUMAN["arms_crossed"],
             "Sujeto en la arena de la playa (baja escaleras del malecón). Solo el sujeto + el trazo de luz. Mar y cielo como fondo negro.",
             "Bulb 25s a f/8 ISO 100. Playa de noche = oscuridad casi total salvo el faro de La Marina. El sujeto quieto, asistente traza espirales alrededor. Minimalismo extremo: sujeto + luz, nada más.",
             ["Baja a la playa con permiso (revisar mareas)", "Lleva linterna LED pequeña + guante para no quemar", "Sujeto lleva ropa oscura"],
             ["No apuntes la linterna al lente", "No muevas el sujeto entre la iluminación y el final"],
             {"lens": "35mm", "aperture": "f/22", "shutter": "Bulb 60", "iso": 100, "notes": "Mañana: imposible sin ND enorme."},
             {"lens": "35mm", "aperture": "f/22", "shutter": "Bulb 30", "iso": 100, "notes": "Tarde: solo en cueva o túnel."},
             {"lens": "35mm", "aperture": "f/8", "shutter": "Bulb 25", "iso": 100, "notes": "Noche: ideal en playa a las 20:00."},
             {"pose": "sit_stay", "action": "Perro sentado en playa, dueño traza luz alrededor"},
             {"pose": "arms_crossed", "action": "Modela con brazos cruzados, asistente traza luz"}),
        shot("B09", "larga_exp", "35-80@50", "f/11", "20\"", 100, 25.0, 500.0,
             "simetria", "central", 1.65,
             POSES_HUMAN["walking_candid"],
             "Cámara en trípode apuntando al horizonte del mar. 20s: el mar se convierte en niebla, las nubes en streaks, el sujeto caminando desaparece casi completamente.",
             "20s a f/11 ISO 100 con trípode. El mar en larga exposición pierde olas y se vuelve bruma. Sujeto caminando queda como ghost casi invisible. Simetría: horizonte perfecto al centro (excepción a la regla de tercios, justificada por simetría mar-cielo).",
             ["Trípode en roca firme (no arena suelta)", "Disparador remoto o 2s retardados", "Si hay sol: ND10 para 20s"],
             ["No dispares con marea subiendo cerca de ti", "No toques la cámara durante la exposición"],
             {"lens": "35-80mm @50", "aperture": "f/16", "shutter": "20", "iso": 100, "notes": "Mañana: ND10 obligatorio."},
             {"lens": "35-80mm @50", "aperture": "f/16", "shutter": "20", "iso": 100, "notes": "Tarde: hora dorada, ND8."},
             {"lens": "35-80mm @50", "aperture": "f/11", "shutter": "30", "iso": 200, "notes": "Noche: sin ND, 30s para más efecto niebla."},
             {"pose": "walking_candid", "action": "Perro caminando por la orilla, ghost en niebla"},
             {"pose": "walking_candid", "action": "Modela caminando por la orilla, ghost"}),
        shot("B10", "zooming", "35-80", "f/11", "3\"", 100, 6.0, 50.0,
             "punto_interes", "central", 1.55,
             POSES_HUMAN["portrait_3_4"],
             "Sujeto a 6 m contra el faro de La Marina al fondo. Durante 3s gira el zoom de 35 a 80mm. El faro queda como estallido radial, el sujeto como punto fijo.",
             "3s a f/11 ISO 100. El giro del zoom crea líneas radiales desde el centro. El faro lejano se estira más (mayor cambio angular relativo). El sujeto al centro queda relativamente estable.",
             ["Practica el giro: uniforme, ni muy rápido ni muy lento", "Sujeto al centro exacto", "Trípode obligatorio"],
             ["No muevas la cámara mientras haces zoom", "No uses tiempos >5s — el efecto se diluye"],
             {"lens": "35-80mm", "aperture": "f/16", "shutter": "3", "iso": 100, "notes": "Mañana: ND8 necesario."},
             {"lens": "35-80mm", "aperture": "f/16", "shutter": "3", "iso": 100, "notes": "Tarde dorada: efecto más cálido."},
             {"lens": "35-80mm", "aperture": "f/8", "shutter": "3", "iso": 800, "notes": "Noche: faroles crean explosiones luminosas."},
             {"pose": "sit_stay", "action": "Perro sentado quieto al centro"},
             {"pose": "portrait_3_4", "action": "Modela 3/4 al centro, muy quieta"}),
    ],
}


# ===========================================================================
# PLAN C — Casa + Calle de San Isidro (Noche controlada)
# ===========================================================================
PLAN_C = {
    "id": "plan_c",
    "name": "San Isidro Nocturno — Interior + Calle Urbana",
    "location": "Interior controlado + exteriores públicos seguros de San Isidro",
    "distance_from_home": "Sesión local; elige una ruta pública y segura",
    "best_window": "Noche 19:30–22:30 · Después de las 18:00 en invierno (La Garúa)",
    "why": "Un interior controlado ofrece dominio de luz y oscuridad para lightpainting, ghost y zooming. Una calle pública segura con faroles y tránsito visible permite practicar barrido y trazas sin revelar una ubicación residencial.",
    "palette": ["#1a1a2e", "#16213e", "#e94560", "#f5f5f5"],
    "shots": [
        shot("C01", "mucha_pdc", 35, "f/11", "1/60", 800, 3.5, 8.0,
             "capas", "central", 1.55,
             POSES_HUMAN["portrait_3_4"],
             "Interior de la casa: sala con vista al jardín. Sujeto a 3.5 m, fondo: muebles + ventana al jardín con farol lejano. Capas: sofá (FG), sujeto (mid), ventana+jardín (BG).",
             "35mm en interior es ideal (no demasiado angular). f/11 con ISO 800 da 1/60s — suficiente para evitar trepidación si el sujeto se mantiene quieto. Las capas construyen profundidad: sofá, sujeto, ventana-jardín.",
             ["Sube ISO a 800-1600 si necesario, prioridad a f/11", "Usa luz ambiente (no flash directo) para mantener atmósfera", "Enciende lámparas cálidas para crear capas de luz"],
             ["No uses flash directo — mata la atmósfera cálida", "No dispares a 1/15 sin trípode — saldrá trepidado"],
             {"lens": "35mm", "aperture": "f/11", "shutter": "1/60", "iso": 800, "notes": "Mañana: luz natural de ventana, ISO 200 suficiente."},
             {"lens": "35mm", "aperture": "f/11", "shutter": "1/30", "iso": 400, "notes": "Tarde: mezcla luz ventana + lámparas."},
             {"lens": "35mm", "aperture": "f/8", "shutter": "1/30", "iso": 1600, "notes": "Noche: solo lámparas de casa, sube ISO a 1600-3200."},
             {"pose": "sit_stay", "action": "Perro sentado en alfombra, mirando al dueño"},
             {"pose": "portrait_3_4", "action": "Modela 3/4 en sofá, mirada directa"}),
        shot("C02", "mucha_pdc", "35-80@50", "f/8", "1/30", 800, 5.0, 12.0,
             "simetria", "central", 1.65,
             POSES_HUMAN["arms_crossed"],
             "Pasillo central de la casa o escalera simétrica. Sujeto al centro exacto, elementos laterales idénticos (cuadros, lámparas).",
             "El zoom a 50mm comprime un poco más que el prime 35mm, ideal para pasillos. f/8 da PDC suficiente. La simetría requiere nivel perfecto y sujeto centrado.",
             ["Usa nivel del 6D (en LiveView)", "Enciende todas las luces simétricas", "Si no hay simetría arquitectónica, créala con dos lámparas iguales"],
             ["No dispares descentrado", "No rompas la simetría con un objeto extra en un lado"],
             {"lens": "35-80mm @50", "aperture": "f/8", "shutter": "1/30", "iso": 800, "notes": "Mañana: luz lateral puede romper simetría."},
             {"lens": "35-80mm @50", "aperture": "f/8", "shutter": "1/30", "iso": 800, "notes": "Tarde: igual, cuidado con sombras laterales."},
             {"lens": "35-80mm @50", "aperture": "f/5.6", "shutter": "1/15", "iso": 3200, "notes": "Noche: con lámparas simétricas, ISO 3200."},
             {"pose": "sit_stay", "action": "Perro sentado al centro del pasillo"},
             {"pose": "arms_crossed", "action": "Modela brazos cruzados al centro"}),
        shot("C03", "poca_pdc", 85, "f/1.8", "1/125", 800, 2.5, 6.0,
             "punto_interes", "central", 1.55,
             POSES_HUMAN["candid_laugh"],
             "Retrato en casa con fondo de lámpara encendida a 6 m. La lámpara sale como bokeh circular brillante.",
             "85mm f/1.8 a 2.5 m: PDC ~6 cm. La lámpara del fondo se convierte en círculos de luz (bokeh) — efecto clásico de retrato nocturno. El ojo es el único punto de interés.",
             ["Apaga otras luces para que solo la lámpara del fondo destaque", "Equilibra con luz suave frontal (ventana o reflector blanco)", "Encuentra una lámpara con forma interesante para el bokeh"],
             ["No uses 85mm a f/8 — matas el bokeh", "No dispares con luz frontal dura (flash directo)"],
             {"lens": "85mm", "aperture": "f/2.5", "shutter": "1/125", "iso": 400, "notes": "Mañana: luz natural de ventana frontal."},
             {"lens": "85mm", "aperture": "f/2", "shutter": "1/125", "iso": 400, "notes": "Tarde: lámpara encendida como acento."},
             {"lens": "85mm", "aperture": "f/1.8", "shutter": "1/60", "iso": 1600, "notes": "Noche: solo la lámpara del fondo + luz suave frontal."},
             {"pose": "head_tilt", "action": "Perro cabeza ladeada, ojos fijos"},
             {"pose": "candid_laugh", "action": "Modela riendo, lámpara de fondo"}),
        shot("C04", "poca_pdc", 50, "f/1.8", "1/60", 800, 2.5, 5.0,
             "espacio_neg", "central", 1.40,
             POSES_HUMAN["looking_back"],
             "Sujeto de espaldas mirando por la ventana a la calle iluminada. Mucho espacio vacío a la derecha (la pared).",
             "50mm a 2.5 m y f/1.8 da PDC ~10 cm. El espacio negativo es la pared oscura a la derecha (3/4 del encuadre). El sujeto en el tercio izquierdo, mirando hacia el espacio NEGATIVO.",
             ["Subexpón para preservar las luces de la calle por la ventana", "Pide al sujeto que gire solo la cabeza, no el cuerpo", "El contraste luz interior/sombra hace el espacio negativo"],
             ["No llenes el espacio negativo con cuadros o muebles", "No dispares frontal — pierde el 'sobre el hombro'"],
             {"lens": "50mm", "aperture": "f/2.2", "shutter": "1/60", "iso": 400, "notes": "Mañana: luz exterior fuerte, contraste alto."},
             {"lens": "50mm", "aperture": "f/1.8", "shutter": "1/60", "iso": 800, "notes": "Tarde: luces exteriores empiezan a encenderse."},
             {"lens": "50mm", "aperture": "f/1.8", "shutter": "1/30", "iso": 1600, "notes": "Noche: luces de calle + faroles, perfecto."},
             {"pose": "backlit_silhouette", "action": "Perro de perfil contra ventana iluminada"},
             {"pose": "looking_back", "action": "Modela girada sobre el hombro hacia la ventana"}),
        shot("C05", "congelado", 50, "f/2", "1/2000", 1600, 4.0, 10.0,
             "minimalismo", "contrapicado", 0.50,
             POSES_HUMAN["jumping_joy"],
             "Sujeto saltando en el patio/jardín de la casa de noche. Solo un farol ilumina. Cámara baja mirando arriba contra cielo oscuro.",
             "1/2000s congela el salto. ISO 1600 compensa la poca luz. f/2 da margen de PDC en movimiento. Contrapicado aísla al sujeto contra el cielo. Minimalismo: solo sujeto+cielo.",
             ["Usa un farol potente o linterna direccional como luz principal", "Pre-enfoca donde saltará el sujeto (MF)", "Dispara en ráfaga, captura el pico del salto"],
             ["No dispares sin luz direccional — saldrá oscuro", "No uses 1/500 — saldrá borroso"],
             {"lens": "50mm", "aperture": "f/4", "shutter": "1/4000", "iso": 200, "notes": "Mañana: luz natural, fácil."},
             {"lens": "50mm", "aperture": "f/2.8", "shutter": "1/2000", "iso": 800, "notes": "Tarde: sol bajo, contraste alto."},
             {"lens": "50mm", "aperture": "f/2", "shutter": "1/2000", "iso": 3200, "notes": "Noche: con farol fuerte, ISO 3200-6400."},
             {"pose": "jumping_catch", "action": "Perro saltando a atrapar snack"},
             {"pose": "jumping_joy", "action": "Modela saltando, brazos arriba"}),
        shot("C06", "barrido", 50, "f/8", "1/30", 800, 8.0, 30.0,
             "tercios", "central", 1.0,
             POSES_HUMAN["running_dynamic"],
             "Calle urbana pública de noche: auto o motocicleta pasando. Cámara sigue el movimiento. Streaks de faroles detrás.",
             "1/30s con seguimiento. El 50mm a 8 m encuadra un auto completo. f/8 ISO 800 da exposición correcta con faroles. Sujeto en tercio derecho, moviéndose hacia la izquierda (espacio libre).",
             ["Posiciónate en la vereda donde los autos pasan predeciblemente (cruce o semáforo)", "Gira el torso siguiendo al auto", "Cuidado con tu seguridad: no te bajes de la vereda"],
             ["No dispares con ISO 100 — saldrá oscura", "No uses 1/250 — congela el auto"],
             {"lens": "50mm", "aperture": "f/11", "shutter": "1/125", "iso": 200, "notes": "Mañana: autos a velocidad alta, 1/125 mantiene algo de barrido."},
             {"lens": "50mm", "aperture": "f/8", "shutter": "1/60", "iso": 400, "notes": "Tarde: luz baja, ISO 400, 1/60."},
             {"lens": "50mm", "aperture": "f/4", "shutter": "1/30", "iso": 1600, "notes": "Noche: faroles crean streaks luminosos preciosos."},
             {"pose": "running_fetch", "action": "Perro corriendo en vereda (con correa por seguridad)"},
             {"pose": "running_dynamic", "action": "Ciclista o auto pasando"}),
        shot("C07", "fantasma", 35, "f/11", "4\"", 200, 4.0, 12.0,
             "enmarcado", "central", 1.55,
             POSES_HUMAN["candid_laugh"],
             "Sujeto en sala, marco natural de puerta abierta. 4s: sujeto ríe (movimiento de cabeza y manos sale como ghost), muebles quietos nítidos.",
             "4s a f/11 ISO 200 con trípode. Sujeto enmarca la puerta abierta (enmarcado natural). El movimiento de cabeza y manos al reír produce ghosts sobre el cuerpo quieto. La puerta crea profundidad.",
             ["Trípode obligatorio", "Pide al sujeto: ríe suave, no muevas el cuerpo", "Enciende lámparas cálidas para mantener luz ambiente"],
             ["No dispares sin trípode", "No expongas más de 6s — el fantasma se desvanece"],
             {"lens": "35mm", "aperture": "f/16", "shutter": "4", "iso": 100, "notes": "Mañana: ND8 necesario para 4s."},
             {"lens": "35mm", "aperture": "f/16", "shutter": "4", "iso": 100, "notes": "Tarde: posible sin ND."},
             {"lens": "35mm", "aperture": "f/11", "shutter": "4", "iso": 200, "notes": "Noche: con lámparas interiores, ideal."},
             {"pose": "play_bow", "action": "Perro en play bow, cola en movimiento (ghost) cuerpo quieto"},
             {"pose": "candid_laugh", "action": "Modela riendo suavemente, ghost en cabeza"}),
        shot("C08", "lightpainting", 35, "f/8", "Bulb 30\"", 100, 4.0, 8.0,
             "punto_interes", "central", 1.40,
             POSES_HUMAN["arms_crossed"],
             "Habitación totalmente a oscuras. Sujeto quieto. Asistente traza contorno del sujeto + espirales alrededor con linterna LED.",
             "Bulb 30s a f/8 ISO 100. Oscuridad total. El sujeto emerge del negro solo donde la luz lo toca. Punto de interés único: el contorno luminoso del sujeto. Tres capas: contorno, espiral externa, fondo negro.",
             ["Apaga TODAS las luces, hasta el LED del router (cúbrelo)", "Sujeto: respira suave, no te muevas 30s", "Lleva guante para no quemarte con la linterna; apágala al cambiar dirección"],
             ["No apuntes la linterna al lente (flare)", "No uses ISO alto — se quema"],
             {"lens": "35mm", "aperture": "f/22", "shutter": "Bulb 60", "iso": 100, "notes": "Mañana: imposible sin ND enorme, mejor de noche."},
             {"lens": "35mm", "aperture": "f/22", "shutter": "Bulb 60", "iso": 100, "notes": "Tarde: habitación oscura con cortinas cerradas, posible."},
             {"lens": "35mm", "aperture": "f/8", "shutter": "Bulb 30", "iso": 100, "notes": "Noche: ideal, habitación totalmente a oscuras."},
             {"pose": "sit_stay", "action": "Perro sentado muy quieto, dueño traza contorno"},
             {"pose": "arms_crossed", "action": "Modela brazos cruzados, asistente traza luz"}),
        shot("C09", "larga_exp", "35-80@35", "f/11", "20\"", 200, 15.0, 100.0,
             "perspectiva", "central", 1.65,
             POSES_HUMAN["walking_candid"],
             "Calle urbana pública de noche, cámara en trípode desde una zona peatonal segura. 20s: faroles como estrellas y autos como líneas rojas/blancas.",
             "20s a f/11 ISO 200 con trípode. La perspectiva de la calle crea líneas convergentes hacia el fondo. La larga exposición transforma los autos en streaks de luz. Sujeto caminando desaparece casi por completo (ghost).",
             ["Trípode en vereda firme (no al borde)", "Disparador remoto", "Encuadra con la calle desapareciendo en perspectiva"],
             ["No te muevas durante la exposición", "No dispares si hay mucho viento (vibración en trípode)"],
             {"lens": "35-80mm @35", "aperture": "f/16", "shutter": "10", "iso": 100, "notes": "Mañana: ND10 obligatorio para 10s."},
             {"lens": "35-80mm @35", "aperture": "f/16", "shutter": "10", "iso": 100, "notes": "Tarde: ND8 o ND10."},
             {"lens": "35-80mm @35", "aperture": "f/11", "shutter": "20", "iso": 200, "notes": "Noche: ideal, faroles como estrellas de 6 puntas."},
             {"pose": "walking_candid", "action": "Perro caminando por vereda, ghost imperceptible"},
             {"pose": "walking_candid", "action": "Modela caminando, ghost"}),
        shot("C10", "zooming", "35-80", "f/11", "3\"", 200, 6.0, 20.0,
             "capas", "central", 1.55,
             POSES_HUMAN["portrait_3_4"],
             "Sujeto a 6 m en la sala, lámparas encendidas a diferentes distancias. Durante 3s gira el zoom de 35 a 80mm. Cada lámpara crea su propio estallido radial.",
             "3s a f/11 ISO 200. El giro del zoom crea líneas radiales desde el centro. Las lámparas a diferentes distancias (capas de luz) generan estallidos de diferente longitud. Sujeto al centro queda estable.",
             ["Practica el giro uniformemente", "Sujeto al centro exacto", "Trípode obligatorio"],
             ["No muevas la cámara mientras haces zoom", "No uses más de 5s"],
             {"lens": "35-80mm", "aperture": "f/16", "shutter": "3", "iso": 100, "notes": "Mañana: ND8 necesario."},
             {"lens": "35-80mm", "aperture": "f/16", "shutter": "3", "iso": 100, "notes": "Tarde: ND4 o ND8."},
             {"lens": "35-80mm", "aperture": "f/8", "shutter": "3", "iso": 800, "notes": "Noche: con lámparas interiores, ISO 800."},
             {"pose": "sit_stay", "action": "Perro sentado al centro, muy quieto"},
             {"pose": "portrait_3_4", "action": "Modela 3/4 al centro, muy quieta"}),
    ],
}


# ===========================================================================
# PLAN D — Centro Histórico de Lima / Plaza San Martín
# ===========================================================================
PLAN_D = {
    "id": "plan_d",
    "name": "Centro Histórico — Plaza San Martín & Jirón de la Unión",
    "location": "Plaza San Martín, Jirón de la Unión, Plaza Mayor (Centro de Lima)",
    "distance_from_home": "Salida urbana; planifica transporte y retorno nocturno",
    "best_window": "Mañana 07:00–09:00 (menos gente, luz dorada) · Tarde 16:00–18:00",
    "why": "Arquitectura colonial-republicana simétrica, arcos de la Plaza San Martín, jirón peatonal con perspectiva forzada, palomas en Plaza Mayor. Perfecto para simetría arquitectónica, enmarcado con arcos, perspectiva con líneas convergentes, panning de transeúntes.",
    "palette": ["#8b5a2b", "#d4a574", "#5a3a1a", "#f5e6d3"],
    "shots": [
        shot("D01", "mucha_pdc", 35, "f/11", "1/250", 200, 5.0, 30.0,
             "perspectiva", "central", 1.65,
             POSES_HUMAN["walking_candid"],
             "Jirón de la Unión peatonal. Cámara en eje central de la calle. Balcones coloniales a ambos lados convergen al fondo (cúpula de la Catedral visible).",
             "35mm en FF: FoV amplio suficiente para abarcar la calle. f/11 da PDC de 2.5 m a infinito. La perspectiva de un solo punto (cámara en eje) crea líneas convergentes de balcones, cornisas y banderas hacia el fondo. El sujeto caminando da escala.",
             ["Encuadra PERFECTAMENTE en el eje central de la calle", "Espera un momento sin demasiada gente (temprano)", "Subexpón -0.3 EV para preservar luces del cielo al fondo"],
             ["No dispares descentrado — las líneas no convergerán correctamente", "No uses gran angular extremo (24mm) — distorsiona demasiado los balcones"],
             {"lens": "35mm", "aperture": "f/11", "shutter": "1/250", "iso": 200, "notes": "Mañana: 7-8am luz lateral cálida, menos gente."},
             {"lens": "35mm", "aperture": "f/11", "shutter": "1/125", "iso": 400, "notes": "Tarde: luz dorada, más gente — espera momentos vacíos."},
             {"lens": "35mm", "aperture": "f/8", "shutter": "1/15", "iso": 1600, "notes": "Noche: faroles del jirón, triple difícil por gente."},
             {"pose": "walking_candid", "action": "Perro caminando con correa por el jirón"},
             {"pose": "walking_candid", "action": "Modela caminando por el eje central"}),
        shot("D02", "mucha_pdc", "35-80@35", "f/8", "1/200", 200, 8.0, 25.0,
             "simetria", "central", 1.70,
             POSES_HUMAN["arms_crossed"],
             "Plaza San Martín: sujeto al centro exacto de la plaza, cámara en eje del monumento. Edificios simétricos (Club Nacional y Hotel Bolívar) a ambos lados.",
             "El zoom a 35mm f/8 da PDC suficiente para el monumento lejano. La simetría exige posición exacta: sujeto al centro, cámara alineada con el monumento. Plaza amplia permite la distancia de 8 m.",
             ["Usa rejilla de pantalla y nivel electrónico del 6D", "Equilibra la luz: si hay sol lateral, espera nube o usa sombra", "Verifica simetría en LiveView antes de disparar"],
             ["No dispares descentrado", "No rompas la simetría con peatones asimétricos — espera el momento"],
             {"lens": "35-80mm @35", "aperture": "f/8", "shutter": "1/200", "iso": 200, "notes": "Mañana: mejor momento, plaza vacía."},
             {"lens": "35-80mm @35", "aperture": "f/8", "shutter": "1/100", "iso": 400, "notes": "Tarde: sombras largas pueden romper simetría."},
             {"lens": "35-80mm @35", "aperture": "f/5.6", "shutter": "1/15", "iso": 1600, "notes": "Noche: iluminación del monumento, cuidado con WB."},
             {"pose": "sit_stay", "action": "Perro sentado al centro exacto de la plaza"},
             {"pose": "arms_crossed", "action": "Modela brazos cruzados al centro"}),
        shot("D03", "poca_pdc", 85, "f/1.8", "1/500", 200, 2.5, 12.0,
             "punto_interes", "central", 1.55,
             POSES_HUMAN["portrait_3_4"],
             "Retrato 3/4 contra la fachada del Hotel Bolívar o Club Nacional. Fachada arquitectónica detallada desenfocada como textura.",
             "85mm a 2.5 m y f/1.8: PDC ~6 cm. La fachada colonial a 12 m se convierte en textura marrón-crema uniforme. El sujeto es el único punto nítido de interés.",
             ["Enfoca el ojo más cercano con punto central + recomposición suave", "Si hay sol directo, busca sombra del arco para luz pareja", "Dispara en ráfaga para variaciones de gesto"],
             ["No uses 85mm a f/8 — matas el bokeh de la fachada", "No dispares contraluz sin reflector"],
             {"lens": "85mm", "aperture": "f/2", "shutter": "1/1000", "iso": 200, "notes": "Mañana: sombra de arco, luz suave."},
             {"lens": "85mm", "aperture": "f/1.8", "shutter": "1/500", "iso": 200, "notes": "Tarde dorada: fachada brilla."},
             {"lens": "85mm", "aperture": "f/1.8", "shutter": "1/60", "iso": 3200, "notes": "Noche: con iluminación del monumento, ISO alto."},
             {"pose": "head_tilt", "action": "Perro con cabeza ladeada, fachada colonial de fondo"},
             {"pose": "portrait_3_4", "action": "Modela 3/4, fachada de fondo"}),
        shot("D04", "poca_pdc", 50, "f/1.8", "1/250", 200, 3.0, 6.0,
             "enmarcado", "central", 1.40,
             POSES_HUMAN["s_curve_standing"],
             "Sujeto enmarcado por uno de los arcos de la Plaza San Martín o pasaje Ovalo. El arco cerca de la cámara, desenfocado, enmarca al sujeto.",
             "50mm a 3 m y f/1.8: el arco a 1 m está MUY desenfocado, el sujeto a 3 m nítido en su plano, el fondo a 6 m suavemente borroso. Tres planos definidos.",
             ["Encuadra el arco de forma asimétrica (no centrado)", "Espera la luz adecuada: sol lateral ilumina el arco por dentro", "El sujeto NO debe estar pegado al arco — necesita 2 m de separación"],
             ["No tapes al sujeto con el arco (debe enmarcar, no cubrir)", "No dispares a f/4 — el arco saldrá demasiado nítido"],
             {"lens": "50mm", "aperture": "f/2", "shutter": "1/500", "iso": 200, "notes": "Mañana: luz lateral del arco, ideal."},
             {"lens": "50mm", "aperture": "f/1.8", "shutter": "1/250", "iso": 200, "notes": "Tarde dorada: arco cálido, sujeto iluminado."},
             {"lens": "50mm", "aperture": "f/1.8", "shutter": "1/30", "iso": 3200, "notes": "Noche: iluminación interior del arco, mágico."},
             {"pose": "lying_down", "action": "Perro echado bajo el arco, enmarcado"},
             {"pose": "s_curve_standing", "action": "Modela S-curve bajo el arco"}),
        shot("D05", "congelado", 85, "f/2.8", "1/2500", 400, 10.0, 100.0,
             "minimalismo", "contrapicado", 0.60,
             POSES_HUMAN["jumping_joy"],
             "Sujeto saltando en Plaza Mayor contra cielo despejado. Cámara baja mirando hacia arriba. Palomas en vuelo pueden sumarse.",
             "1/2500s congela el salto + las palomas en vuelo. 85mm a 10 m encuadra medio cuerpo en el aire. Contrapicado aísla al sujeto contra el cielo azul. Minimalismo por eliminación.",
             ["AF AI Servo + punto central + burst", "Coordina salto con movimiento de palomas (un asistente las asusta)", "Pre-enfoca en la altura esperada del salto"],
             ["No dispares a 1/500 — palomas y salto saldrán blur", "No uses f/1.8 — fallarás enfoque en movimiento"],
             {"lens": "85mm", "aperture": "f/4", "shutter": "1/4000", "iso": 200, "notes": "Mañana: cielo azul, sombras duras."},
             {"lens": "85mm", "aperture": "f/2.8", "shutter": "1/2500", "iso": 400, "notes": "Tarde dorada: cielo cálido."},
             {"lens": "85mm", "aperture": "f/2.8", "shutter": "1/1250", "iso": 6400, "notes": "Noche: muy difícil, mejor día."},
             {"pose": "jumping_catch", "action": "Perro saltando a atrapar snack en plaza"},
             {"pose": "jumping_joy", "action": "Modela saltando, palomas en vuelo"}),
        shot("D06", "barrido", 50, "f/11", "1/30", 100, 8.0, 40.0,
             "tercios", "central", 1.0,
             POSES_HUMAN["running_dynamic"],
             "Peatón o ciclista en Jirón de la Unión. Cámara sigue el movimiento. Fachadas coloniales en streaks horizontales.",
             "1/30s con seguimiento. 50mm a 8 m encuadra medio cuerpo en movimiento. El sujeto en el tercio derecho entrante. f/11 da margen para fallos de seguimiento. Las fachadas en streaks crean dinamismo.",
             ["Posiciónate donde los peatones pasen predeciblemente (esquina)", "Gira torso: prep → dispara → continúa 1s", "Punto central AF + AI Servo + burst"],
             ["No pares el giro al disparar", "No uses 1/250 — congela todo"],
             {"lens": "50mm", "aperture": "f/11", "shutter": "1/30", "iso": 100, "notes": "Mañana: luz fuerte, ideal."},
             {"lens": "50mm", "aperture": "f/8", "shutter": "1/30", "iso": 200, "notes": "Tarde dorada: streaks cálidos."},
             {"lens": "50mm", "aperture": "f/4", "shutter": "1/30", "iso": 1600, "notes": "Noche: faroles crean streaks luminosos."},
             {"pose": "running_fetch", "action": "Perro corriendo por jirón (con correa por seguridad)"},
             {"pose": "running_dynamic", "action": "Ciclista o corredor pasando"}),
        shot("D07", "fantasma", 35, "f/11", "3\"", 100, 5.0, 20.0,
             "enmarcado", "picado", 1.80,
             POSES_HUMAN["thinking_seated"],
             "Sujeto sentado en un banco de la plaza, enmarcado por el monumento. 3s: sujeto quieto nítido, transeúntes detrás como ghosts.",
             "3s a f/11 ISO 100. Sujeto quieto en banco, transeúntes detrás ghosts. El monumento enmarca el encuadre. Picado ligero muestra los adoquines.",
             ["Trípode obligatorio", "Pide al sujeto: respira suave, no te muevas", "Toma 5-6 versiones para elegir el mejor ghost"],
             ["No dispares sin trípode", "No dispares con viento fuerte — el pelo sale blur"],
             {"lens": "35mm", "aperture": "f/16", "shutter": "3", "iso": 100, "notes": "Mañana: ND10 obligatorio, difícil."},
             {"lens": "35mm", "aperture": "f/16", "shutter": "3", "iso": 100, "notes": "Tarde: hora dorada, posible sin ND."},
             {"lens": "35mm", "aperture": "f/8", "shutter": "3", "iso": 400, "notes": "Noche: con iluminación del monumento, perfecto."},
             {"pose": "sit_stay", "action": "Perro sentado quieto en banco, peatones ghosts detrás"},
             {"pose": "thinking_seated", "action": "Modela sentada pensando, peatones ghosts"}),
        shot("D08", "lightpainting", 35, "f/8", "Bulb 25\"", 100, 5.0, 25.0,
             "minimalismo", "central", 1.0,
             POSES_HUMAN["arms_crossed"],
             "Sujeto en una esquina oscura de la plaza (lejos de faroles). Asistente traza con linterna. Solo sujeto + trazo de luz, fondo arquitectónico negro.",
             "Bulb 25s a f/8 ISO 100. Esquina oscura de la plaza. El sujeto emerge del negro. Minimalismo extremo: solo el contorno luminoso.",
             ["Encuentra la esquina más oscura (lejos de faroles)", "Sujeto: muy quieto 25s", "Lleva guante para no quemarte con la linterna"],
             ["No apuntes la linterna al lente", "No uses ISO alto — se quema"],
             {"lens": "35mm", "aperture": "f/22", "shutter": "Bulb 60", "iso": 100, "notes": "Mañana: imposible sin ND enorme."},
             {"lens": "35mm", "aperture": "f/22", "shutter": "Bulb 30", "iso": 100, "notes": "Tarde: solo en zona muy sombreada."},
             {"lens": "35mm", "aperture": "f/8", "shutter": "Bulb 25", "iso": 100, "notes": "Noche: ideal, esquina oscura de la plaza."},
             {"pose": "sit_stay", "action": "Perro sentado muy quieto, dueño traza luz"},
             {"pose": "arms_crossed", "action": "Modela brazos cruzados, asistente traza luz"}),
        shot("D09", "larga_exp", "35-80@50", "f/11", "20\"", 100, 20.0, 200.0,
             "capas", "central", 1.65,
             POSES_HUMAN["walking_candid"],
             "Cámara en trípode apuntando a la Plaza Mayor desde la galería. 20s: palomas como ghosts, autos lejanos como streaks, adoquines nítidos, fuentes del agua en niebla.",
             "20s a f/11 ISO 100. Las palomas en vuelo desaparecen, los autos lejanos se estiran en líneas rojas. Las capas: adoquines (FG), fuente (mid), Catedral (BG). La larga exposición transforma la escena caótica en algo onírico.",
             ["Trípode en roca firme (no madera de bancas)", "Disparador remoto", "Encuadra con la Catedral al fondo para anclar la composición"],
             ["No dispares con viento fuerte", "No toques la cámara durante la exposición"],
             {"lens": "35-80mm @50", "aperture": "f/16", "shutter": "15", "iso": 100, "notes": "Mañana: ND10 obligatorio para 15s."},
             {"lens": "35-80mm @50", "aperture": "f/16", "shutter": "15", "iso": 100, "notes": "Tarde: ND8 suficiente."},
             {"lens": "35-80mm @50", "aperture": "f/11", "shutter": "20", "iso": 200, "notes": "Noche: con iluminación del monumento, ideal."},
             {"pose": "walking_candid", "action": "Perro caminando por la plaza, ghost imperceptible"},
             {"pose": "walking_candid", "action": "Modela caminando, ghost"}),
        shot("D10", "zooming", "35-80", "f/11", "3\"", 100, 7.0, 40.0,
             "perspectiva", "central", 1.55,
             POSES_HUMAN["portrait_3_4"],
             "Sujeto a 7 m contra la fachada iluminada de la Catedral. Durante 3s gira el zoom de 35 a 80mm. La fachada se estira en estallido radial.",
             "3s a f/11 ISO 100. Giro del zoom crea líneas radiales desde el centro. La fachada iluminada se convierte en estallido. Sujeto al centro queda relativamente estable.",
             ["Practica el giro uniformemente", "Sujeto al centro exacto", "Trípode obligatorio"],
             ["No muevas la cámara durante el zoom", "No uses más de 5s"],
             {"lens": "35-80mm", "aperture": "f/16", "shutter": "3", "iso": 100, "notes": "Mañana: ND8 obligatorio."},
             {"lens": "35-80mm", "aperture": "f/16", "shutter": "3", "iso": 100, "notes": "Tarde: ND4 o ND8."},
             {"lens": "35-80mm", "aperture": "f/8", "shutter": "3", "iso": 800, "notes": "Noche: fachada iluminada, ISO 800."},
             {"pose": "sit_stay", "action": "Perro sentado quieto al centro"},
             {"pose": "portrait_3_4", "action": "Modela 3/4 al centro, muy quieta"}),
    ],
}



# ===========================================================================
# PLAN E — Home / Building Lab · climate-proof, repeatable A/B practice
# ===========================================================================
PLAN_E = {
    "id": "plan_e",
    "name": "Home / Building Lab — Control Total",
    "location": "Interior controlado + ventana o retiro privado seguro",
    "distance_from_home": "Sin ubicación fija; usa un espacio con permiso",
    "best_window": "Cualquier hora · ideal con garúa, poco tiempo o para repetir pruebas A/B",
    "why": "Recupera el plan clima-proof de la primera versión: pasillos, puertas, escaleras y ventanas permiten controlar geometría, seguridad y repetición. Es el mejor laboratorio para aprender qué cambia cuando mueves UNA sola variable.",
    "palette": ["#263238", "#607D8B", "#C9A227", "#ECE7DC"],
    "shots": [
        shot("E01", "mucha_pdc", 35, "f/11", "1/125", 800, 3.5, 8.0, "capas", "central", 0.80, POSES_HUMAN["portrait_3_4"],
             "Pasillo: planta/silla a ≥2 m, sujeto a ~3.5–4 m y puerta/fondo al final. Tres planos claramente separados.",
             "El objetivo no es simplemente cerrar a f/11: necesitas geometría real de foreground/medio/fondo. Con 35mm la escena conserva contexto y f/11 amplía la zona aceptablemente nítida.",
             ["Mantén el foreground al menos ~2 m del sensor", "Enfoca cerca de 4 m y revisa foreground + fondo al 100%", "Sube ISO antes que dejar caer demasiado la velocidad si el sujeto está vivo"],
             ["No pongas un objeto a 20 cm y esperes que f/11 lo haga nítido", "No evalúes PDC sólo en la pantalla pequeña"],
             {"lens":"35mm","aperture":"f/11","shutter":"1/125","iso":800,"notes":"Día: usa luz de ventana; evita mezclar demasiadas temperaturas."},
             {"lens":"35mm","aperture":"f/11","shutter":"1/125","iso":1600,"notes":"Tarde: prioriza 1/125 si el sujeto puede moverse."},
             {"lens":"35mm","aperture":"f/8","shutter":"1/80","iso":3200,"notes":"Noche: acepta ISO mayor o usa sujeto/objeto totalmente estático."},
             {"pose":"sit_stay","action":"Perro quieto a media distancia, no pegado al fondo"},
             {"pose":"portrait_3_4","action":"Persona pequeña dentro del entorno; no llenar el cuadro"}),
        shot("E02", "mucha_pdc", 35, "f/8", "1/125", 800, 5.0, 10.0, "simetria", "central", 1.20, POSES_HUMAN["arms_crossed"],
             "Escalera/corredor perfectamente frontal: eje central, barandas/puertas repetidas, sujeto pequeño al fondo.",
             "La simetría depende más de colocar el sensor perpendicular y centrado que del lente. 35mm incluye suficientes líneas para que el punto de fuga sea evidente.",
             ["Activa la cuadrícula y nivela antes de disparar", "Muévete lateralmente hasta que ambos lados sean equivalentes"],
             ["No corrijas una cámara mal ubicada sólo recortando después", "No confundas nadir con cenital: aquí la cámara es frontal"],
             {"lens":"35mm","aperture":"f/8","shutter":"1/125","iso":800,"notes":"Día: corredor con luz de ventana."},
             {"lens":"35mm","aperture":"f/8","shutter":"1/100","iso":1600,"notes":"Tarde: conserva simetría, no subexpongas por miedo al ISO."},
             {"lens":"35mm","aperture":"f/8","shutter":"1/60","iso":3200,"notes":"Noche: trípode si no hay sujeto en movimiento."},
             {"pose":"sit_stay","action":"Perro centrado al fondo como escala"},
             {"pose":"arms_crossed","action":"Power stance centrado, hombros simétricos"}),
        shot("E03", "poca_pdc", 85, "f/1.8", "1/500", 1600, 3.0, 11.0, "tercios", "central", 1.55, POSES_HUMAN["portrait_3_4"],
             "Retrato junto a ventana; sujeto a ~3 m y fondo del corredor/habitación al menos 8 m detrás.",
             "A 85mm f/1.8 y ~3 m la DoF es muy estrecha. El gran salto visual viene de alejar el fondo: no de abrir 1/3 de stop con el sujeto pegado a una pared.",
             ["One Shot y foco en el ojo cercano", "Mueve al sujeto hacia delante para aumentar sujeto↔fondo"],
             ["No pegues al sujeto a la pared", "No uses 1/60 con persona/perro vivo sólo porque el lente es luminoso"],
             {"lens":"85mm","aperture":"f/1.8","shutter":"1/500","iso":800,"notes":"Día: ventana lateral; cuida altas luces."},
             {"lens":"85mm","aperture":"f/1.8","shutter":"1/500","iso":1600,"notes":"Tarde: mantén shutter y deja subir ISO."},
             {"lens":"85mm","aperture":"f/1.8","shutter":"1/320","iso":6400,"notes":"Noche: busca una fuente suave grande o reubica cerca de ventana/lámpara."},
             {"pose":"head_tilt","action":"Perro a nivel de ojos, fondo del corredor muy lejos"},
             {"pose":"portrait_3_4","action":"Cuerpo 3/4, ojo cercano al plano de foco"}),
        shot("E04", "poca_pdc", 50, "f/1.8", "1/250", 1600, 2.2, 8.0, "enmarcado", "central", 1.45, POSES_HUMAN["leaning_wall"],
             "Marco de puerta cerca del lente; sujeto ~2–2.5 m; pared/fondo al menos 5 m detrás del sujeto.",
             "El marco cercano se desenfoca, el sujeto cae en el plano nítido y el fondo vuelve a desenfocarse: tres zonas visuales sin necesitar un tele largo.",
             ["Deja visible cara/ojos completos dentro del marco", "Mueve primero al sujeto y luego afina el encuadre"],
             ["No dejes que el marco corte ojos/manos de forma accidental", "No pegues al sujeto al fondo"],
             {"lens":"50mm","aperture":"f/1.8","shutter":"1/320","iso":800,"notes":"Día: marco claro + fondo más oscuro funciona muy bien."},
             {"lens":"50mm","aperture":"f/1.8","shutter":"1/250","iso":1600,"notes":"Tarde: usa luz lateral de puerta/ventana."},
             {"lens":"50mm","aperture":"f/1.8","shutter":"1/200","iso":3200,"notes":"Noche: acerca luz, no sujeto al fondo."},
             {"pose":"standing_alert","action":"Perro dentro del marco, ojos despejados"},
             {"pose":"leaning_wall","action":"Apoyo ligero en marco, cuello largo y hombro relajado"}),
        shot("E05", "congelado", 50, "f/2.8", "1/1600", 3200, 5.0, 12.0, "punto_interes", "contrapicado", 0.60, POSES_HUMAN["jumping_joy"],
             "Salto corto, tela o cabello en movimiento en un área sin piso resbaloso. Cámara baja y espacio alrededor.",
             "En interior el costo real es ISO. Para cumplir 'congelado', conserva primero 1/1600–1/2000; f/2.8 da más tolerancia de foco que f/1.8.",
             ["AI Servo + punto central + ráfaga", "Pre-sigue antes del salto", "Usa movimiento pequeño y repetible"],
             ["No sacrifiques el shutter para bajar ISO", "No hagas saltar al perro en piso liso"],
             {"lens":"50mm","aperture":"f/2.8","shutter":"1/2000","iso":1600,"notes":"Día: cerca de ventana grande."},
             {"lens":"50mm","aperture":"f/2.8","shutter":"1/1600","iso":3200,"notes":"Tarde: ISO alto es preferible a motion blur."},
             {"lens":"50mm","aperture":"f/2.8","shutter":"1/1000","iso":6400,"notes":"Noche: si no hay luz suficiente, pospón esta toma."},
             {"pose":"jumping_catch","action":"Sólo si el perro tiene superficie segura y controlada"},
             {"pose":"jumping_joy","action":"Salto corto o giro de tela/cabello"}),
        shot("E06", "barrido", 35, "f/8", "1/40", 800, 4.0, 10.0, "perspectiva", "central", 1.00, POSES_HUMAN["running_dynamic"],
             "Cruce lateral por pasillo; líneas de paredes/puertas se convierten en streaks.",
             "El pasillo es un laboratorio perfecto porque la trayectoria puede ser casi paralela al sensor. Empieza 1/60 y baja a 1/40; 1/30 es el siguiente escalón si el fondo sigue demasiado congelado.",
             ["Gira desde la cintura antes-durante-después", "Mantén el mismo detalle del sujeto bajo el punto AF"],
             ["No pares al oír el obturador", "No subas a 1/250 para 'arreglar' el blur: destruirías el efecto"],
             {"lens":"35mm","aperture":"f/8","shutter":"1/40","iso":400,"notes":"Día: si sobra luz, cierra más o busca sombra."},
             {"lens":"35mm","aperture":"f/8","shutter":"1/40","iso":800,"notes":"Tarde: ideal para repetir series."},
             {"lens":"35mm","aperture":"f/5.6","shutter":"1/40","iso":1600,"notes":"Noche: líneas de luces ayudan a visualizar el barrido."},
             {"pose":"walking_candid","action":"Perro caminando lateral, no corriendo en piso liso"},
             {"pose":"running_dynamic","action":"Persona camina/trota lateral de forma repetible"}),
        shot("E07", "fantasma", 35, "f/8", "1 s", 100, 4.0, 10.0, "simetria", "central", 1.25, POSES_HUMAN["walking_candid"],
             "Cámara fija en pasillo; fondo estructural inmóvil; una PERSONA cruza durante ~1 s.",
             "El efecto se lee porque el fondo queda nítido y el sujeto ocupa cada posición sólo una fracción de la exposición. En la versión 'perro', el perro queda fuera: una persona es el mover controlable.",
             ["Trípode + temporizador 2 s", "Prueba 0.5 / 1 / 2 s cambiando sólo la velocidad del sujeto"],
             ["No muevas la cámara", "No uses al perro como sujeto móvil si no puedes controlar exactamente la trayectoria"],
             {"lens":"35mm","aperture":"f/16","shutter":"1","iso":100,"notes":"Día: puede requerir sombra o ND."},
             {"lens":"35mm","aperture":"f/11","shutter":"1","iso":100,"notes":"Tarde: muy controlable en pasillo."},
             {"lens":"35mm","aperture":"f/8","shutter":"1","iso":200,"notes":"Noche: suficiente luz para leer el fondo."},
             {"pose":"walking_candid","action":"Perro fuera; usa una persona caminando por el cuadro"},
             {"pose":"walking_candid","action":"Camina transversalmente; micro-pausa si sale demasiado tenue"}),
        shot("E08", "lightpainting", 35, "f/8", "10 s", 100, 4.0, 10.0, "minimalismo", "central", 1.20, POSES_HUMAN["arms_crossed"],
             "Sala oscura: pre-enfoca con luz, pasa a MF, apaga luz de enfoque y dibuja alrededor de un objeto/persona quieta.",
             "Diez segundos son un excelente punto de partida: suficiente tiempo para un trazo limpio sin exigir inmovilidad extrema. El control de interior facilita repetir.",
             ["Pre-enfoca → MF antes de apagar luces", "Temporizador/remoto", "Mantén la linterna en movimiento"],
             ["No apuntes luz intensa a ojos del perro/persona", "No muevas el trípode"],
             {"lens":"35mm","aperture":"f/11","shutter":"10","iso":100,"notes":"Día: oscurece por completo el ambiente."},
             {"lens":"35mm","aperture":"f/8","shutter":"10","iso":100,"notes":"Tarde: control de cortinas/luces."},
             {"lens":"35mm","aperture":"f/8","shutter":"10","iso":100,"notes":"Noche: escenario ideal."},
             {"pose":"sit_stay","action":"Sólo si el perro permanece tranquilo; mejor objeto/juguete estático"},
             {"pose":"arms_crossed","action":"Silueta simple para que el trazo sea legible"}),
        shot("E09", "larga_exp", 35, "f/11", "10 s", 100, 10.0, 40.0, "capas", "central", 1.25, POSES_HUMAN["portrait_3_4"],
             "Desde ventana/retiro protegido: trazas de tráfico y arquitectura fija; apagar luces interiores si disparas a través de vidrio.",
             "La larga exposición necesita contraste entre elementos inmóviles y movimiento continuo. 5–15 s es un rango inicial más útil que intentar 30 s por defecto.",
             ["Trípode estable y cámara completamente fuera de la calzada", "Revisa altas luces e histograma", "Evita reflejos interiores en vidrio"],
             ["No incluyas al perro en la zona de tráfico", "No toques la cámara durante la exposición"],
             {"lens":"35mm","aperture":"f/16","shutter":"5","iso":100,"notes":"Día: ND fuerte si quieres segundos."},
             {"lens":"35mm","aperture":"f/11","shutter":"5","iso":100,"notes":"Blue hour: equilibrio excelente entre ciudad y trazas."},
             {"lens":"35mm","aperture":"f/11","shutter":"10","iso":100,"notes":"Noche: ajusta a 5–15 s según densidad de tráfico."},
             {"pose":"sit_stay","action":"Perro fuera de la toma; prioridad a seguridad y trazas"},
             {"pose":"portrait_3_4","action":"Humano opcional sólo si está inmóvil y lejos del borde"}),
        shot("E10", "zooming", "35-80", "f/8", "2 s", 100, 4.0, 12.0, "punto_interes", "central", 1.25, POSES_HUMAN["arms_crossed"],
             "Luces interiores o fachada vista desde ventana; punto de interés en el centro; trípode; girar 35→80 y luego 80→35.",
             "f/8 está disponible en todo el rango del EF 35–80 f/4–5.6 III y evita que la apertura variable del zoom sea la limitación. El centro se desplaza menos visualmente durante el zoom.",
             ["Pre-enfoca el centro y pasa a MF", "Gira sólo el anillo de zoom, no la cámara", "Haz series a 1 / 2 / 4 s"],
             ["No uses fondo uniforme", "No coloques el punto principal lejos del centro en el primer intento"],
             {"lens":"35-80mm","aperture":"f/11","shutter":"2","iso":100,"notes":"Día: ND/sombra si necesitas 2 s."},
             {"lens":"35-80mm","aperture":"f/8","shutter":"2","iso":100,"notes":"Tarde: luces puntuales empiezan a destacar."},
             {"lens":"35-80mm","aperture":"f/8","shutter":"2","iso":100,"notes":"Noche: ideal; prueba ambos sentidos del zoom."},
             {"pose":"sit_stay","action":"Objeto o perro sólo si puede quedarse inmóvil en el centro"},
             {"pose":"arms_crossed","action":"Pose frontal simple y centrada"}),
    ],
}

# ===========================================================================
# PLAN F — Abtao / San Isidro financial district · restored local urban route
# ===========================================================================
PLAN_F = {
    "id": "plan_f",
    "name": "Abtao / Distrito Financiero — Urbano Local",
    "location": "Parque Combate de Abtao + ejes peatonales/arquitectura del distrito financiero de San Isidro",
    "distance_from_home": "Ruta urbana pública; define el punto de partida de forma privada",
    "best_window": "16:15–19:30 · arquitectura con luz lateral → blue hour → trazas",
    "why": "Recupera una fortaleza de la primera versión: arquitectura corporativa, líneas geométricas, parque y tráfico en una sola ruta cercana, perfecta para simetría, contrapicado, barrido y larga exposición.",
    "palette": ["#243447", "#4B6478", "#A67C52", "#DDE3E7"],
    "shots": [
        shot("F01", "mucha_pdc", 35, "f/11", "1/160", 200, 4.0, 14.0, "capas", "contrapicado", 0.65, POSES_HUMAN["arms_crossed"],
             "Edificio + bolardo/planta/línea de vereda en primer plano + sujeto medio + fachada al fondo.",
             "Tres planos reales enseñan PDC mejor que sólo cerrar diafragma. El contrapicado moderado enfatiza líneas sin convertir verticales en una distracción extrema.",
             ["Foreground ≥2 m si quieres que siga legible", "Corrige posición antes de inclinar más la cámara"],
             ["No pongas la cámara en la calzada", "No exageres contrapicado si las verticales dominan al sujeto"],
             {"lens":"35mm","aperture":"f/11","shutter":"1/250","iso":200,"notes":"Día: luz lateral en fachada."},
             {"lens":"35mm","aperture":"f/11","shutter":"1/160","iso":400,"notes":"Tarde: conservar 3 planos."},
             {"lens":"35mm","aperture":"f/8","shutter":"1/80","iso":1600,"notes":"Noche: trípode si escena sin sujeto móvil."},
             {"pose":"standing_alert","action":"Perro a ~4–5 m como escala, siempre en zona segura"},
             {"pose":"arms_crossed","action":"Power stance pequeño respecto a la arquitectura"}),
        shot("F02", "mucha_pdc", 35, "f/8", "1/160", 200, 5.0, 14.0, "simetria", "central", 1.35, POSES_HUMAN["arms_crossed"],
             "Fachada/pasillo frontal con eje exacto y líneas repetidas.",
             "La simetría exige sensor paralelo/perpendicular a la geometría relevante. El 35mm permite mostrar el patrón completo sin alejarte demasiado.",
             ["Cuadrícula + nivel electrónico", "Mueve pies milimétricamente antes de recortar"],
             ["No confundas simetría con simplemente poner sujeto al centro"],
             {"lens":"35mm","aperture":"f/8","shutter":"1/250","iso":200,"notes":"Día."},
             {"lens":"35mm","aperture":"f/8","shutter":"1/160","iso":400,"notes":"Tarde."},
             {"lens":"35mm","aperture":"f/8","shutter":"1/60","iso":1600,"notes":"Noche: trípode si hace falta."},
             {"pose":"sit_stay","action":"Perro centrado pequeño para dar escala"},
             {"pose":"arms_crossed","action":"Frontal, centrado, hombros equilibrados"}),
        shot("F03", "poca_pdc", 85, "f/1.8", "1/500", 200, 3.0, 15.0, "tercios", "central", 1.45, POSES_HUMAN["portrait_3_4"],
             "Retrato en parque con torres/árboles muy separados detrás; sujeto en tercio mirando hacia espacio libre.",
             "85mm f/1.8 a ~3 m aísla, pero el fondo sólo se 'derrite' de verdad si está físicamente lejos. El lente no cambia la perspectiva por sí solo: tu posición de cámara sí.",
             ["Foco en ojo cercano", "Fondo ≥8 m detrás; ideal 10–15 m"],
             ["No pegues al sujeto a edificios/arbustos"],
             {"lens":"85mm","aperture":"f/1.8","shutter":"1/800","iso":100,"notes":"Día."},
             {"lens":"85mm","aperture":"f/1.8","shutter":"1/500","iso":200,"notes":"Tarde dorada."},
             {"lens":"85mm","aperture":"f/1.8","shutter":"1/320","iso":3200,"notes":"Noche: busca fachada iluminada lejana."},
             {"pose":"head_tilt","action":"Perro en tercio, mirada hacia espacio negativo"},
             {"pose":"portrait_3_4","action":"3/4, mirada hacia zona negativa"}),
        shot("F04", "poca_pdc", 50, "f/1.8", "1/320", 200, 2.2, 10.0, "enmarcado", "central", 1.40, POSES_HUMAN["leaning_wall"],
             "Columnas/portal como marco cercano; sujeto separado del fondo.",
             "50mm f/1.8 conserva suficiente arquitectura para entender el marco sin que el retrato se vuelva demasiado ambiental.",
             ["Marco delante, sujeto ~2–2.5 m, fondo ≥5 m detrás", "Evita tangencias con cabeza/hombros"],
             ["No apoyes al sujeto contra la pared del fondo"],
             {"lens":"50mm","aperture":"f/1.8","shutter":"1/500","iso":100,"notes":"Día."},
             {"lens":"50mm","aperture":"f/1.8","shutter":"1/320","iso":200,"notes":"Tarde."},
             {"lens":"50mm","aperture":"f/1.8","shutter":"1/200","iso":1600,"notes":"Noche."},
             {"pose":"standing_alert","action":"Perro entre columnas, ojo nítido"},
             {"pose":"leaning_wall","action":"Apoyo ligero en columna, no colapsar hombros"}),
        shot("F05", "congelado", 85, "f/2.8", "1/2000", 400, 8.0, 20.0, "espacio_neg", "contrapicado", 0.60, POSES_HUMAN["jumping_joy"],
             "Carrera/salto en parque, lejos de tránsito; espacio delante del movimiento.",
             "1/2000 s es la variable no negociable; 85mm desde ~8 m reduce el cambio angular aparente y da más tiempo para seguir con el AF de 11 puntos de la 6D.",
             ["AI Servo + punto central + ráfaga", "Pre-sigue 1–2 s antes"],
             ["No dirijas al perro hacia la avenida", "No abras a f/1.8 si la tasa de acierto cae"],
             {"lens":"85mm","aperture":"f/2.8","shutter":"1/2000","iso":400,"notes":"Día/tarde."},
             {"lens":"85mm","aperture":"f/2.8","shutter":"1/2000","iso":800,"notes":"Tarde."},
             {"lens":"85mm","aperture":"f/2.8","shutter":"1/1000","iso":6400,"notes":"Noche: mejor posponer si falta luz."},
             {"pose":"running_fetch","action":"Perro cruza lateralmente en área verde segura"},
             {"pose":"jumping_joy","action":"Salto corto o carrera lateral"}),
        shot("F06", "barrido", 50, "f/8", "1/40", 100, 8.0, 20.0, "tercios", "central", 1.10, POSES_HUMAN["running_dynamic"],
             "Ciclista/corredor cruza lateralmente desde vereda segura; ventanas y columnas crean streaks legibles.",
             "El fondo con líneas repetidas hace el éxito del barrido evidente. 1/40 es un punto inicial robusto; baja a 1/30 si todavía se ve congelado.",
             ["Trayectoria lateral casi paralela", "Gira cintura y continúa después del clic"],
             ["No dirijas al perro junto al tráfico", "No persigas sólo con brazos"],
             {"lens":"50mm","aperture":"f/11","shutter":"1/40","iso":100,"notes":"Día."},
             {"lens":"50mm","aperture":"f/8","shutter":"1/40","iso":100,"notes":"Tarde."},
             {"lens":"50mm","aperture":"f/4","shutter":"1/40","iso":800,"notes":"Noche: luces del fondo ayudan."},
             {"pose":"walking_candid","action":"Para versión perro, practica dentro del parque, no al borde vial"},
             {"pose":"running_dynamic","action":"Corredor/ciclista lateral, gesto natural"}),
        shot("F07", "fantasma", 35, "f/8", "1 s", 100, 5.0, 14.0, "simetria", "central", 1.20, POSES_HUMAN["walking_candid"],
             "Eje arquitectónico fijo; persona cruza o avanza durante 1 s; perro fuera de la toma.",
             "La arquitectura rígida funciona como control visual: si el fondo también se mueve, es trepidación, no 'fantasma'.",
             ["Trípode + 2 s timer", "Prueba 0.5, 1 y 2 s"],
             ["No uses al perro como sujeto móvil cerca de peatones/tráfico"],
             {"lens":"35mm","aperture":"f/16","shutter":"1","iso":100,"notes":"Día: sombra/ND."},
             {"lens":"35mm","aperture":"f/11","shutter":"1","iso":100,"notes":"Tarde."},
             {"lens":"35mm","aperture":"f/8","shutter":"1","iso":200,"notes":"Noche."},
             {"pose":"walking_candid","action":"Perro fuera; una persona crea el ghost"},
             {"pose":"walking_candid","action":"Camina transversal o hacia el eje"}),
        shot("F08", "lightpainting", 35, "f/8", "10 s", 100, 5.0, 12.0, "minimalismo", "central", 1.20, POSES_HUMAN["arms_crossed"],
             "Portal/interior controlado; si el espacio público está ocupado, vuelve a casa para esta toma.",
             "El control de oscuridad y seguridad importa más que conservar la misma locación para las 10 fotos.",
             ["Pre-enfoca → MF", "Trazos simples primero"],
             ["No apuntes linterna fuerte a ojos"],
             {"lens":"35mm","aperture":"f/16","shutter":"10","iso":100,"notes":"Día: sólo interior oscuro/ND."},
             {"lens":"35mm","aperture":"f/11","shutter":"10","iso":100,"notes":"Tarde."},
             {"lens":"35mm","aperture":"f/8","shutter":"10","iso":100,"notes":"Noche ideal."},
             {"pose":"sit_stay","action":"Perro sólo si permanece cómodo; mejor objeto estático"},
             {"pose":"arms_crossed","action":"Silueta limpia para envolver con luz"}),
        shot("F09", "larga_exp", 35, "f/11", "8 s", 100, 12.0, 60.0, "capas", "central", 1.25, POSES_HUMAN["portrait_3_4"],
             "Trazas vehiculares y edificios desde un retiro/vereda protegida; ningún animal en la toma.",
             "5–15 s deja suficientes autos para líneas continuas sin exigir una exposición extrema. Blue hour conserva detalle del entorno.",
             ["Trípode totalmente dentro de zona peatonal segura", "Revisa altas luces", "Prueba 5, 8, 12 s"],
             ["No pongas trípode en calzada/ciclovía", "No incluyas al perro"],
             {"lens":"35mm","aperture":"f/16","shutter":"5","iso":100,"notes":"Día: ND fuerte."},
             {"lens":"35mm","aperture":"f/11","shutter":"5","iso":100,"notes":"Blue hour."},
             {"lens":"35mm","aperture":"f/11","shutter":"8","iso":100,"notes":"Noche."},
             {"pose":"sit_stay","action":"Perro fuera de la toma"},
             {"pose":"portrait_3_4","action":"Persona opcional lejos del borde; prioridad a trazas"}),
        shot("F10", "zooming", "35-80", "f/8", "2 s", 100, 6.0, 20.0, "punto_interes", "central", 1.30, POSES_HUMAN["arms_crossed"],
             "Fachada iluminada/patrón de ventanas con punto central fuerte; trípode; 35→80 y 80→35.",
             "El zoom EF 35–80 es el lente correcto porque la focal puede cambiar DURANTE la exposición. f/8 está disponible a ambos extremos del zoom.",
             ["Centro fuerte", "Pre-enfoca y pasa a MF", "Giro continuo del anillo"],
             ["No muevas la cámara", "No uses una pared uniforme sin luces/patrón"],
             {"lens":"35-80mm","aperture":"f/11","shutter":"2","iso":100,"notes":"Día: ND."},
             {"lens":"35-80mm","aperture":"f/8","shutter":"2","iso":100,"notes":"Tarde."},
             {"lens":"35-80mm","aperture":"f/8","shutter":"2","iso":100,"notes":"Noche ideal."},
             {"pose":"sit_stay","action":"Perro sólo si quieto y centrado; no es necesario"},
             {"pose":"arms_crossed","action":"Frontal simple, centro exacto"}),
    ],
}

PLANS = [PLAN_A, PLAN_B, PLAN_C, PLAN_D, PLAN_E, PLAN_F]

# ---------------------------------------------------------------------------
# Export to JSON helper (used by the export script)
# ---------------------------------------------------------------------------
def to_dict():
    return {
        "gear": GEAR,
        "composition_rules": COMPOSITION_RULES,
        "camera_angles": CAMERA_ANGLES,
        "techniques": TECHNIQUES,
        "poses_human": POSES_HUMAN,
        "poses_dog": POSES_DOG,
        "field_baselines": FIELD_BASELINES,
        "plans": PLANS,
    }


if __name__ == "__main__":
    import json
    from pathlib import Path
    root = Path(__file__).resolve().parents[1]
    out = root / "data" / "plans.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(to_dict(), ensure_ascii=False, indent=2), encoding="utf-8")
    n = sum(len(p["shots"]) for p in PLANS)
    print(f"✓ Wrote {out} ({n} shots across {len(PLANS)} plans)")
